export const coursesSeed = [
  {
    id: 1,
    name: "Matemática I",
    info: "Elementos de lógica proposicional y de primer orden: Enfoque sintáctico y semántico. Técnicas de prueba. Teoría de la Estructuras Discretas. Definiciones y pruebas estructurales. Estructura de las pruebas formales. Teoría básica de conjuntos. Inducción matemática sobre números naturales. Relaciones binarias: relaciones de orden, relaciones de equivalencia, relaciones funcionales. Elementos básicos de análisis combinatorio.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 2,
    name: "Introducción a la Programación",
    info: "Qué es un programa. Las herramientas del programador: entornos de ejecución y de desarrollo. Paradigmas de Programación: Imperativo, Orientado a Objetos, Funcional, Lógico. Principios de la programación imperativa: acciones y comandos, valores y expresiones, tipos, estado. Terminación y parcialidad. Precondiciones como metodología para desarrollo de software robusto. Principios de la programación estructurada: funciones y procedimientos. Necesidad de darle una estructura a un programa no trivial. Resolución de problemas y algoritmos mediante programas. Estructuras de control. Estructuras de datos básicas: listas y registros.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 3,
    name: "Organización de Computadoras",
    info: "Representación de la información: alfanumérico, numérico, punto fijo y flotante, AS-CII. Representación de los datos a nivel máquina. Error. Lenguaje Ensamblador. Sistema de numeración binario. Aritmética de las computadoras: Unidades. Funcionamiento y organización. Arquitectura de Von Neumann. Organización funcional. Unidades funcionales: Unidad Central de Proceso, Unidad de Control, memorias, ciclo de instrucciones, direccionamiento, subsistema de Memoria. Periféricos: conceptos y principio de funcionamiento. Procesadores de Entrada/Salida. Lógica digital: tablas de verdad, equivalencia de fórmulas proposicionales, circuitos combinatorios, circuitos secuenciales. Máquinas algorítmicas. Arquitectura del computador: Componentes de la CPU, memoria principal y secundaria. Subsistema de Entrada/Salida. Lenguaje Máquina. Código fuente y código objeto.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 4,
    name: "Nuevos Entornos y Lenguajes",
    info: "Web 2.0. - Web 3.0. Lectura y escritura en la nube: hipertextualidad e hipermedialidad. Búsqueda de información: criterios, análisis e interpretación de fuentes de información. Escritura colaborativa. Nuevas formas de producir conocimiento en las redes. Comunidad de práctica. Lenguaje audiovisual: producción e interpretación. Narrativas transmedia: convergencia de formatos. Convergencia tecnológica. Inteligencia colectiva.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 5,
    name: "Estructuras de Datos",
    info: "Recursión sobre listas y árboles. Programas recursivos. Tipos abstractos de datos. Tipos algebraicos: maybe, either, enumerativos, listas, árboles binarios, árboles generales. Estructuras de datos. Estructuras contenedoras: pilas, colas, diccionarios, heaps, árboles balanceados, contenedores basados en representaciones numéricas. Representación de datos en memoria. Nociones de representación e invariante de representación y su utilidad en el diseño e implementación de estructuras de datos. Uso imperativo de estructuras de datos. Iteración en listas y árboles. Modelo de memoria imperativo: stack/heap, alocación de memoria. Punteros. Variables por referencia. Listas encadenadas y sus variantes. árboles implementados con punteros. Binary heaps implementadas con arrays. Hashing. Análisis de eficiencia e implementación. Algoritmos de recorrido, ordenamiento, búsqueda, ordenamiento y actualización. Clasificación e implementación. Nociones básicas de algoritmos sobre grafos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 6,
    name: "Programación con Objetos I",
    info: "Conceptos fundantes del paradigma: objeto y mensaje. Concepto de polimorfismo en objetos, comprensión de las ventajas de aprovecharlo. Protocolo/interfaz, concepto de tipo en objetos, comprensión de que un objeto puede asumir distintos tipos. La interfaz como contrato al que se comprometen ciertos objetos, posibilidad de reforzar ese contrato. Estado en el paradigma de objetos: referencias, conocimiento, estado interno. Métodos, clases, herencia, method lookup. Conceptos de responsabilidad y delegación. Colecciones: conceptualización como objetos, caracterización a partir de los conceptos de protocolo y responsabilidad, protocolo, acceso a sus elementos. Testeo automático y repetible. Nociones básicas sobre manejo de errores. Interrupción del flujo de ejecución: modelado mediante estructuras de control, concepto de excepción.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 7,
    name: "Bases de Datos",
    info: "Qué es un modelo de datos, modelos conceptuales, lógicos y físicos. Modelo de entidad-relación: conceptos básicos. Modelo relacional: tabla, atributo, dominio, valor, fila; restricciones de integridad; operaciones que se pueden hacer. SQL: concepto de lenguaje de consulta, sintaxis, concepto de join, agrupamientos, subqueries, joins parciales. Sistemas de Bases de Datos. Diseño y administración de Sistemas de Bases de Datos. Escalabilidad, eficiencia y efectividad. Lenguajes de DBMS. Transacción: concepto, demarcación de transacciones.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 8,
    name: "Inglés I",
    info: "Introducción a la lectura de textos auténticos de géneros específicos de las distintas disciplinas. Estrategias de lectura para la comprensión global de textos escritos en inglés: palabras clave, transparentes, repetidas e índices tipográficos. Palabras conceptuales y estructurales. Organización textual, tema y despliegue temático. Anticipación y predicción. Elaboración del tópico del texto. Técnicas de lectura veloz: skimming y scanning. Cohesión y coherencia. Referentes contextuales: anafóricos y catafóricos; elipsis. Morfología: sufijos y prefijos. Categoría de palabras. Estructura de la información en la definición. Definición de objetos y procesos. Definiciones expandidas. El sintagma nominal. Usos del gerundio (-ing) y del participio pasado (-ed). Instrucciones. Relaciones lógicas entre proposiciones: adición, contraste, causa y efecto, enumeración. Tiempos verbales simples.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 9,
    name: "Matemática II",
    info: "Matrices, determinantes y sistemas de ecuaciones lineales. Estructuras algebraicas: monoides, semigrupos y grupos. Espacios vectoriales de dimensión finita. Aritmética entera y modular. Sistemas de coordenadas en el plano y el espacio. Definición de punto, recta y plano. Caracterización de curvas en el plano y el espacio. Secciones cónicas y Superficies cuádricas. Definiciones y pruebas estructurales. Álgebra lineal y geometría analítica.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 10,
    name: "Programación con Objetos II",
    info: "Aproximación al diseño de software. Noción de decisión de diseño, el diseño como proceso de toma de decisiones. Conceptos de acoplamiento y cohesión. Problemas que derivan de un grado de acoplamiento inadecuado. Vinculación entre las ideas básicas de diseño y el paradigma de objetos. Características deseadas en un diseño de objetos. Patrones de diseño. Nociones sobre proceso de diseño. Eventos. Metaprogramación. Uso de un entorno integrado de software. Notación UML de los diagramas de clases, de objetos y de secuencia. Testeo unitario y automático. Manejo de errores, impacto del manejo de errores en el diseño.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 11,
    name: "Redes de Computadoras",
    info: "Concepto de red de computadoras, redes y comunicación. Modelos en capas, modelo OSI, modelo de Internet. Conceptos de protocolo y de servicio. Nivel físico: dispositivos, cableado estructurado. Nivel de enlace: concepto de enlace, tramas, puentes, enlaces inalámbricos. Nivel de red: concepto de ruteo, topologías, algoritmos de ruteo, protocolos IP, resolución de direcciones. Nivel de transporte: funciones, protocolos UDP y TCP, multiplexación, concepto de socket, control de congestión. Modelo general de Internet: integración de niveles y protocolos, servicios de red (http, dhcp, dns, smtp, etc.). Protocolos de integración. El modelo computacional de la Web. Estándares utilizados en Internet, concepto de RFC. Concepto e implementación de las VPN. Administración de redes: servicios, firewalls. Sistemas cliente/servidor y sus variantes.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 12,
    name: "Sistemas Operativos",
    info: "Introducción a los sistemas operativos: función de abstracción del hardware; organización, estructura y servicios de los SO. Sistemas operativos: de tiempo real, embebidos (embedded), distribuidos. Sistemas batch / Multiprogramación / / Sistemas paralelos. Conceptos de proceso, thread y planificación. Concurrencia de ejecución. Interbloqueos. Comunicación y cooperación entre procesos. Deadlocks. Planificación: Algoritmos, criterios. Multiprocesamiento. Administración de memoria: Espacio lógico vs físico, swapping, alocación contigua, paginación, segmentación. Memoria virtual: Paginación bajo demanda, algoritmos de reemplazo de página, thrashing. Sistemas de archivos: Sistemas de archivos. Protección. Manejo de directorios. Concepto de Proceso. Planificación de Procesos. Protección: objetivos, dominio de protección, matriz de acceso y sus implementaciones. Prácticas con distintos sistemas operativos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 13,
    name: "Programación Funcional",
    info: "Nociones generales del paradigma funcional. Valores y expresiones. Las funciones como valores. Sintaxis. Sistema de Tipos Hindley-Milner. Tipos básicos. Constructores de tipos. Polimorfismo. Funciones de alto orden. Currificación. Inducción/Recursión. Definición inductiva de conjuntos. Definición recursiva de funciones sobre esos conjuntos. Demostraciones inductivas. Inducción estructural. Listas como tipo inductivo. Funciones básicas y de alto orden sobre listas. Patrón de recorrido, selección y recursión. Sistemas de Tipos. Ventajas y limitaciones de los lenguajes de programación con tipos. Asignación de tipos a expresiones. Algoritmo de inferencia. Tipos de datos recursivos. Transformación de Programas. Obtención de programas a partir de especificaciones.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 14,
    name: "Construcción de Interfaces de Usuario",
    info: "Variantes en arquitecturas de sistema respecto de la interfaz de usuario (IU): aplicación centralizada, cliente-servidor o distribuida; ejecución en un cliente de aplicación (browser, flash, otros) o mediante un programa específico; concepto de RIA. Arquitecturas web, protocolos y tecnologías asociadas. Modelos de interacción de la IU con su entorno: interfaces orientadas a eventos, pedido-respuesta, basadas en continuations. Aplicaciones client-initiative y application-initiative. Componentes gráficos usuales en interfaces de usuario. Vinculación entre la IU y el modelo de dominio subyacente. Problemática asociada a transformaciones, validaciones, manejo de errores, excepciones, transacciones e identidad. Impacto de la distribución de aplicaciones en la IU, comunicación sincrónica y asincrónica. Navegación y manejo del estado conversacional. REST, estado en sesión. Nociones de usabilidad. Diseño centrado en el usuario.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 15,
    name: "Algoritmos",
    info: "Noción de algoritmo, ejemplos de algoritmos (criba de Eratostenes, mcd, etc). Criterios de selección de un algoritmo. Notación O y W. Análisis teórico del tiempo de ejecución de un algoritmo Análisis práctico del tiempo de ejecución de un algoritmo. Algoritmos Divide y Vencerás. Recursividad. Análisis de procedimientos recursivos. Algoritmos Basados en Programación Dinámica. Estrategias de diseño de algoritmos. Algoritmos Greedy. Algoritmos de Precondicionamiento y Transformación del Dominio. Algoritmos de programación matemática. Uso de Heurísticas en Algoritmos. Algoritmos numéricos y propagación del error. Casos: algoritmo de Huffman, encriptación, compresión, búsqueda, actualización, ordenamiento, estructuras de datos y algoritmos, árboles estrella, matrices. Algoritmos sobre grafos (DFS, BFD, Prim, Kruskal, Dijkstra, Floyd, sort topológico, etc). Algoritmos básicos sobre cadenas: matching, alineamiento, sufijos. Algoritmos concurrentes, distribuidos y paralelos. Estrategias de implementación.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 16,
    name: "Estrategias de Persistencia",
    info: "Problemas vinculados al acceso concurrente a una base de datos (BD). Performance en el acceso a una BD. Modelado y calidad de datos. Concepto de índice. Conceptos de usuario y permiso en una base de datos. Bases de objetos: concepto, panorama, experimentación práctica, comparación con bases de datos relacionales. BD distribuidas para grandes volúmenes de datos, acceso a datos. Transacciones distribuidas. Interacción entre un programa y un mecanismo de persistencia: nociones básicas, problemáticas generales. Mecanismos de acceso y recuperación de objetos persistidos en bases de datos relacionales. Actualización del estado persistente: reachability, cascada. ORM y problemas de mapeo: herencia, relaciones n-m, estrategias no standard. Transacciones a nivel aplicación y de negocio, concepto de unit of work. Cuestiones de performance y concurrencia al acceder a un mecanismo de persistencia desde un programa, lazyness, cache, versionado, lockeo optimista y pesimista.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 17,
    name: "Laboratorio de Sistemas Operativos y Redes",
    info: "Instalación, configuración y operación de distintos servicios relacionados con Internet: servidores de aplicaciones, servidor y cliente de mail, servidor y cliente FTP, firewalls, etc. Servicios de directorio, servidores LDAP, uso desde aplicaciones. Gestión de usuarios y control de accesos en un entorno operativo, impacto en la instalación de aplicaciones, posibilidad de compartir recursos. Sistemas de backup automatizados, políticas de criticidad. Instalación, configuración y operación de repositorios de código. Monitoreo de redes, protocolo SNMP. Técnicas de transmisión de datos, modelos, topologías, algoritmos de ruteo y protocolos. Sistemas operativos de redes. Computación orientada a redes. Sistemas colaborativos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 18,
    name: "Análisis Matemático",
    info: "Funciones. Representación gráfica. Dominio e Imagen. Funciones polinomiales, racionales, exponenciales, logarítmicas, trigonométricas. Función inversa. Composición de funciones. Límite. Continuidad. Derivada. Aplicaciones del teorema del valor medio. Integral definida. Métodos de integración. Regla de L'Hôpital. Aplicaciones de la integral en una variable. Cálculo diferencial e integral en una variable.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 19,
    name: "Lógica y Programación",
    info: "Lógica Proposicional: Lenguaje, Semántica, Mecanismo Deductivo, Metateoremas, Lógica trivaluada. Lógica de Primer Orden: Lenguaje, Semántica, Sistema axiomático, Metateoremas, Indecidibilidad. Programación lógica: Resolución en lógica de primer orden, PROLOG. Fundamentos de inteligencia artificial simbólica y no simbólica. Especificación de Programas: Especificación e implementación de programas, Lógica de Hoare, Corrección de programas. Verificación de algoritmos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 20,
    name: "Elementos de Ingeniería de Software",
    info: "Teoría general de sistemas. Sistemas de información. Metodologías ágiles: actividades, productos, formas de articulación, roles. Ejemplos: Scrum. Metodologías estructuradas: actividades, productos, formas de articulación, roles. Ejemplos: UP. Similitudes y diferencias entre metodologías ágiles y estructuradas. El proceso del software. Concepto de ciclo de vida, relación con distintas metodologías. Métricas: qué son, qué miden, para qué y cuándo sirven. Estimación de esfuerzos. Conceptos de requerimiento funcional y no funcional. Distintos tipos de testing: de unidad, funcional, de sistema, de stress, de carga. Noción de cobertura. Tests automáticos, integración continua, interacción de las actividades de coding y refactor. Noción de TDD. Nociones de riesgo y plan de contingencia. Ingeniería de Software de sistemas de tiempo real.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 21,
    name: "Seguridad de la Información",
    info: "Introducción a la Seguridad de la Información. Conceptos fundamentales y objetivos. Gestión de la Seguridad de la Información. Riesgo: análisis y tratamiento. Seguridad en Redes, elementos de criptografía. Criptografía Simétrica y Asimétrica. Algoritmos de Hash. Infraestructura de Clave Pública. Certificados digitales. Seguridad en Redes. Objetivos. Ataques, Servicios y Mecanismos de Seguridad. Seguridad en Redes Inalámbricas. Control de Acceso Lógico. Controles físicos de seguridad: seguridad en el centro de cómputos. Seguridad en las operaciones. Gestión de usuarios. Control de cambios. Métodos de Evaluación de seguridad: Auditorías, Evaluaciones funcionales, Vulnerability Assessment y Penetration Test. Gestión de Incidentes. Seguridad en Aplicaciones. Vulnerabilidades. Software malicioso. Problemática de las aplicaciones WEB. Leyes, Regulaciones y Estándares. Marcos legales nacional e internacional. Privacidad, Integridad y seguridad en sistemas de información",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 22,
    name: "Materia UNAHUR I",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 23,
    name: "Inglés II",
    info: "Estrategias de lectura para la comprensión detallada de textos pertenecientes a diversos géneros académicos y profesionales vinculados las distintas disciplinas y carreras. Jerarquización de la información textual. Coherencia textual y avance de la información. Cadena léxica y campo semántico. Funciones retóricas: la clasificación, la descripción, la narración. El sintagma verbal; tiempo, voz y aspecto. Textos narrativos y argumentativos. Oraciones condicionales. Relaciones lógicas entre proposiciones: consecuencia, comparación, temporales, espaciales, condicionales. Tiempos verbales progresivos y perfectivos. Verbos modales simples y perfectivos.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 24,
    name: "Matemática III",
    info: "Polinomios. Números complejos. Polinomio de Taylor para funciones de una variable. Conceptos de cálculo diferencial e integral en varias variables: límite doble, continuidad, derivada parcial y direccional, integrales dobles. Fórmula de Taylor en dos variables. Cálculo diferencial e integral en una y varias variables.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 25,
    name: "Programación Concurrente",
    info: "Concurrencia. Los porqués de la concurrencia. Concurrencia y paralelismo. Modelo de memoria compartida, atomicidad e independencia. Manejo de memoria en ejecución. Secciones críticas, locks y barriers, semáforos, monitores y condiciones variables, Rendezvous. Problemas de la concurrencia: Starvation, Deadlocks, Liveness y Progress, Safety, Race-conditions, Fairness. Modelo de pasaje de mensajes: Comunicación sincrónica vs comunicación asincrónica, Modelo de transacciones. Modelos de interacción: Cliente/Servidor, Productor/Consumidor. Aplicación de los conceptos estudiados en lenguajes de programación concretos, mecanismos de sincronización.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 26,
    name: "Ingeniería de Requerimientos",
    info: "Ingeniería de requerimientos. Estrategias para la extracción de requerimientos. Herramientas conceptuales para la organización de requerimientos en modelos. Administración y Control de Proyectos. Análisis basado en casos de uso. Análisis orientado a objetos. Estructuración mediante reglas de negocio, invariantes de clase, workflows, entre otros. Nociones sobre métodos formales. Estrategias de análisis en metodologías ágiles. Validación de requerimientos, relación con testing. Herramientas para la automatización de tests de aceptación. Definición de requerimientos no funcionales: performance, escalabilidad, flexibilidad, usabilidad, testeabilidad, robustez, seguridad, etc. Variación del comportamento del sistema a lo largo del tiempo, diferentes formas de distribución. Comportamiento típico y picos de utilización. Métricas utilizadas.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 27,
    name: "Desarrollo de Aplicaciones",
    info: "Validación y testing de software. Tests de integración. Problemática específica para la automatización de tests de integración, persistencia, interfaz de usuario. Técnicas para diagnóstico de problemas: stacktraces, breakpoints, watchpoints. Manejo de excepciones. Relación con unittesting. Reingeniería de software. Técnicas de refactorización sobre un proyecto funcionando. Migraciones y actualizaciones. Versionado y compartición de programas fuente. Repositorios de código centralizados y distribuidos. Versionado y compartición de bibliotecas y ejecutables. Administración de entregables y dependencias. Repositorios de bibliotecas. Integración continua. Control de cambios. Trazabilidad de requerimientos, errores y cambios de funcionalidad. Herramientas para la administración integral de cambios y correcciones. Aplicación en un proyecto mediano de desarrollo de software.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 28,
    name: "Probabilidad y Estadística",
    info: "Probabilidad y estadística. Estadística descriptiva. Modelos determinísticos y estocásticos. Distribución de probabilidades sobre un espacio muestral. Variables aleatorias discretas y continuas. Distintos tipos de distribuciones. Inferencia estadística. Intervalos de confianza. Varianza. Regresión lineal. Coeficientes de correlación. Ensayos de hipótesis. Números aleatorios. Método Montecarlo.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 29,
    name: "Gestión de Proyectos de Desarrollo de Software",
    info: "Planificación y estimación de proyectos de software. Definición y documentación de las actividades. Priorización y secuenciación de actividades. Dependencias, diagramas de Gantt, en iteraciones, conceitos de sprint y backlog. Asignación de recursos. Monitoreo y seguimiento de proyectos de software. Nociones de aseguramiento de calidad. Calidad de Software: del producto y del proceso. Gestión del equipo de trabajo. Herramientas de colaboración y comunicación interna. Gestión de riesgos. Seguimiento y Control de Riesgos. Gestión de la relación con el cliente. Comunicación y resolución de conflictos. Control de cambios.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 30,
    name: "Lenguajes Formales y Autómatas",
    info: "Lenguajes y gramáticas. Gramáticas e isomorfimos. Jerarquía de Chomsky. Lenguajes regulares. Autómatas. Expresiones regulares. Minimización de autómatas. Analizadores lexicográficos. Lenguajes independientes de contexto. Árboles de derivación. Autómatas de pila. Lenguajes determinísticos. Lenguajes tipo 1 y tipo 0. Máquinas asociadas. Máquinas de Turing. Problema de la detención.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 31,
    name: "Programación con Objetos III",
    info: "Introducción a los sistemas de tipos y chequeo de tipos en un lenguaje de programación con objetos: tipos nominales y estructurales, tipado explícito e implícito. Ducktyping. Inferencia de tipos. Esquemas de binding, early / late binding. Variantes del paradigma de objetos. Bloques y closures. Non-local returns. Herencia simple y múltiple; mixins y traits. Introducción a la programación orientada a aspectos. Open classes. Extensiones del paradigma de objetos. Construcción de programas multilenguaje y multiparadigma. Implicancias en el diseño, patrones de diseño en las diferentes variantes del paradigma, behavioral completeness. Metaprogramación, programación reflexiva, introspección, self-modification. Mirrors. Lenguajes específicos de dominio (DSL). Clasificación de los DSLs: compilados, interpretados; traductores; embebidos. Creación de DSLs. Programación declarativa.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 32,
    name: "Materia UNAHUR II",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 33,
    name: "Práctica Profesional Supervisada",
    info: "Roles y funciones dentro de un equipo. Trabajo en equipo. Autoaprendizaje. Buenas prácticas en la gestión de recursos informáticos. Planificación de recursos. Sistemas de gestión de código integrado. Trabajo en forma remota. Relevamiento y selección de información. Conocer normas, estándares y criterios de calidad. Elaboración de Informes. Exposición de informes.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 34,
    name: "Teoría de la Computación",
    info: "Máquinas de Turing. Máquinas Algorítmicas. Conceptos Básicos de Teoría de Computabilidad y Complejidad: Problemas computables y no computables. Problema de la parada. Problemas tratables e intratables. Conjuntos decidibles, Funciones recursivas. Conjuntos recursivamente enumerables. Reducciones many-one. Clases L, P, PSPACE, NP, NP - completitud. Análisis de Algoritmos: Análisis asintótico, comportamento en el mejor caso, caso promedio y peor caso. Notación 0(). Balance entre tiempo y espacio en los algoritmos. Análisis de Complejidad de Algoritmos. Teoría de base de datos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 35,
    name: "Arquitectura de Software I",
    info: "Arquitectura de software y arquitectura de sistemas. Proceso de definición y evolución de una arquitectura en diferentes metodologías de desarrollo. Requerimientos funcionales y no funcionales, restricciones, influencias, entorno social y técnico, estándares, ferramentas disponibles. Objetivos de una arquitectura. Estilos arquitectónicos. Arquitectura de dominio. Arquitectura y Diseño. Patrones. Patrones arquitecturales para la interfaz de usuario. Integración con el dominio. Internacionalización. Arquitecturas orientadas a servicios. Arquitecturas extensibles. Arquitecturas basadas en plugins. Arquitecturas de seguridad. Estrategias de verificación de arquitecturas. Arquitecturas concurrentes y distribuidas. Herramientas tecnológicas para soportar las decisiones arquitectónicas.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 36,
    name: "Sistemas Distribuidos y Tiempo Real",
    info: "Introducción a los sistemas de procesamiento distribuido y su terminología. Comunicación y sincronización en sistemas distribuidos, pasaje de mensaje y llamadas a procedimiento remoto (rpc). Tiempo, Sincronización y Coordinación Distribuida. Memoria compartida distribuida, asignación de tareas y balance de cargas (Algoritmos básicos). Manejo de Recursos y Sistemas de Archivos en Sistemas Distribuidos. Control de Concurrencia en sistemas distribuidos. Transacciones. Seguridad en sistemas distribuidos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 37,
    name: "Tesina de Licenciatura",
    info: "Determinación de un tema de investigación: pertinencia y factibilidad. Objetivos e hipótesis. Estado del arte, revisión y búsqueda bibliográfica sistematizada. Modelización de un proyecto. Etapas de un proyecto. Estructura de escritura final y formatos de presentación.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 5,
    hsTotal: 160,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 38,
    name: "Materia Optativa I",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 39,
    name: "Características de Lenguajes de Programación",
    info: "Lenguajes según su modelo de cómputo: imperativo, funcional, objetos, lógico. Estructuras de datos en los diferentes paradigmas. Lenguajes según sus características: Lenguajes tipados y no tipados. Mecanismos de binding (estático y dinámico). Mecanismos de pasaje de parámetros (valor, referencia, nombre, otros). Formas de llevar a cabo la ejecución (compilación, interpretación, máquinas virtuales). Formas de administración de memoria (explícita y garbage collection). Lenguajes según su propósito: generales, de dominio específico, de scripting. Lenguajes con semánticas operacional, denotacional, axiomática. Lenguajes de Programación: Entidades y ligaduras. Sistema de Tipos, Niveles de Polimorfismo. Encapsulamiento y Abstracción. Conceptos de Intérpretes y Compiladores. Criterios de Diseño y de Implementación de Lenguajes de Programación. Nociones básicas de semántica formal.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 40,
    name: "Arquitectura de Software II",
    info: "Escalabilidad, eficiencia y efectividad. Dimensionamiento de los requerimientos de hardware y de las necesidades de red de un sistema de software. Técnicas para escalamiento vertical y horizontal. Clustering, balanceo de carga, afinidad, sharding. Estrategias de particionamiento de bases de datos. Tolerancia a fallos. Estrategias de cache de datos. Nociones de minería de datos. Hardware específico para sistemas de gran envergadura. Virtualización. Software y hardware como servicios. Verificación del cumplimiento de los requerimientos no funcionales: performance, tolerancia a fallos, carga. Operación y monitoreo de sistemas. Estrategias de logging para sistemas de gran envergadura. Herramientas para medición de performance. Profiling. Información caliente e información de ciclo de vida largo. Análisis de servicios en red, análisis de tráfico. Herramientas de monitoreo de fallas.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 41,
    name: "Arquitectura de Computadoras",
    info: "Arquitectura y organización de computadoras. Jerarquías de memoria: Memoria segmentada, Memoria virtual. Interrupciones: Concepto y definición. Lenguaje Ensamblador. Tipos de interrupción. Definición de entorno y contexto de un programa. Detección de interrupción: cambio de contexto. Atención de interrupciones. Subsistema de Entrada y salida. Coprocesadores (aritméticos, de video, etc). Procesadores de alta prestación. Nivel de Microarquitectura: Unidad de control, Memoria de control, Microprograma, Microinstrucciones, Cronología de microinstrucciones, Secuenciamiento de microinstrucciones. Tipos de arquitecturas: Arquitectura RISC, arquitectura en paralelo, Pentium, arquitecturas GRID, Arquitecturas multiprocesadores. Conceptos de arquitecturas basadas en servicios. Conceptos de arquitecturas reconfigurables.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 42,
    name: "Materia Optativa II",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 43,
    name: "Parseo y Generación de Código",
    info: "Estructura de compiladores. Compilación vs interpretación. Estructura de un compilador. Análisis léxico. Análisis sintáctico. Métodos ascendentes y descendentes. Tabla de símbolos. Árboles de parsing y árboles de sintaxis abstracta. Tratamiento de errores. Análisis semántico. Verificación de tipos. Generación de código. Optimización de código.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 44,
    name: "Ejercicio Profesional",
    info: "Aspectos Legales y Sociales, Consideraciones generales sobre el ordenamiento jurídico. Responsabilidad ética y profesional. Elementos de las relaciones económicas jurídicas. La propiedad intelectual. Conceptos generales de contratos. Licenciamiento de software y contratos informáticos. Documento digital, firma digital y derecho de Internet. Régimen legal de las bases de datos. Responsabilidad penal: delitos informáticos. Actuación judicial del licenciado en informática. Nociones de auditoría y peritaje. Gobernanza IT.",
    infoUrl: null,
    area: "APyS",
    hsWeekly: 3,
    hsTotal: 48,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 45,
    name: "Tecnología y Sociedad",
    info: "Computación y Sociedad. Modelos de desarrollo científico y tecnológico. El proceso de producción de conocimiento. Etapas históricas. Historia de la computación. Ciencia, tecnología y economía. Sus interrelaciones. Etapas del desarrollo científico y tecnológico. El papel de la Universidad. La investigación científica y tecnológica en la actualidad. Software libre y sociedad. El posicionamiento del software libre y el código abierto.",
    infoUrl: null,
    area: "APyS",
    hsWeekly: 3,
    hsTotal: 48,
    code: null,
    isPlaceholder: false,
  },

  // Optativas Licenciatura en Informática
  {
    id: 60,
    name: "Bases de Datos II",
    info: `Cuestiones de eficiencia en el acceso a bases de datos: transformación de consultas, hints al motor, trabajo sobre índices. Configuraciones de nivel físico en un motor de base de datos relacional, como tablespaces y replicación. Tipos de datos no-standard en bases de datos, como ser blobs o XML. Implementación física de bases de datos relacionales, en particular: manejo eficiente de archivos, implementación de índices usando árboles B y variantes. Conceptos básicos de Data Mining y Datawarehousing.`,
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 61,
    name: "Fundamentos de Aprendizaje Automático",
    info: `Modelos y métodos computacionales. Clasificación de métodos de aprendizaje. Funciones discriminantes. Aprendizaje Supervisado. Aprendizaje no Supervisado. Modelo probabilístico. Criterios de evaluación de rendimiento. Reducción de dimensión. Análisis de aplicaciones basadas en los métodos estudiados.`,
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 62,
    name: "Introducción a la Bioinformática",
    info: `Conceptos básicos de la genética molecular: leyes de la herencia, genética de poblaciones, genética evolutiva, replicación del ADN, mutación y reparación. Acceso remoto a bancos de datos, bancos genéticos. Análisis de secuencias biológicas, algoritmos asociados. Homologías secuenciales y estructurales.`,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 63,
    name: "Políticas Públicas en la Sociedad de la Información y la Era Digital",
    info: `Estado y políticas públicas. Cultura abierta, distribuida, libre, producción colaborativa en red. Derechos en la sociedad de la información. Diferentes iniciativas públicas referentes a los estándares abiertos y al software libre. Diversidad e identidades culturales, diversidad lingüística y contenidos locales. Sociedad de la información y el conocimiento. Proyectos de infraestructura y accesibilidad TIC. Acceso y usos: de la red, de los contenidos. Datos abiertos, gobierno electrónico, gobierno abierto, democracia electrónica. Planteo y eventual desarrollo de algún software relacionado con esta temática. Neutralidad en la red.`,
    infoUrl: null,
    area: "APyS",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 64,
    name: "Sistemas de Información Geográfica",
    info: `Introducción a los Sistemas de Información Geográfica (GIS): objetivos, principales tecnologías utilizadas. Posicionamiento: coordenadas, sistemas de referencia, proyecciones, datums, precisión. Modelos de datos: vectorial, raster, interpolación, implementaciones de formatos (SHP, GeoTIFF, KML, otros). Bases de datos espaciales: tipos de datos, consultas, índices. Servidores de Mapas: protocolos, en particular WMS y WFS; tecnologías. Clientes de Mapas: protocolos y tecnologías. Sistemas de Información Geográfica de Escritorio. Implementación de GIS con tecnologías Open Source: servidor de Bases de Datos, servidor de Mapas, clientes Desktop y Web.`,
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 65,
    name: "Introducción al Desarrollo de Videojuegos",
    info: `Panorama de la historia y estado actual de la industria de videojuegos. Diversidad de videojuegos, géneros mejor establecidos. Concepto de game design, relevancia del relato al pensar el concepto de un juego. Aspectos generales en la concepción de videojuegos. Cuestiones de arquitectura de software y hardware pertinentes para el dominio de videojuegos. El proceso de desarrollo de videojuegos, pertinencia de aplicar conceptos ágiles. Características y bondades del modelado de un juego utilizando los conceptos de la programación con objetos: modelado del dominio en función del game design, modelado del comportamiento aprovechando el polimorfismo, modelado del flujo interactivo usando estados. Relevancia del procesamiento de eventos en varios géneros de juegos. Cuestiones ligadas al tratamiento de gráficos: uso de bibliotecas gráficas y buenas prácticas para su integración en una arquitectura de software, sprites, meshes, frustum, cálculo de colisiones.`,
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 66,
    name: "Análisis Estático de Programas y Herramientas Asociadas",
    info: `Análisis de flujo de datos. Análisis intraprocedural. Análisis interprocedural. Análisis de forma. Análisis basado en restricciones. Análisis abstracto 0-CFA y 0-CFA dirigido por sintaxis. Sistemas de tipos y efectos. Análisis de flujo de control. Inferencia de tipos. Efectos. Comportamiento.`,
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 67,
    name: "Semántica de Lenguajes de Programación",
    info: `Definiciones inductivas. Principios de inducción. Semántica operacional y denotacional de lenguajes imperativos. Ordenes parciales completos. Equivalencia. Semántica axiomática de lenguajes imperativos. Aserciones. Corrección. Reglas de Hoare. Conceptos básicos de teoría de dominios. CPOs, productos, espacio de funciones, lifting, sumas. Semántica operacional y denotación de lenguajes funcionales. Estrategias call-by-value, call-by-name, equivalencia.`,
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 68,
    name: "Administración de las Organizaciones",
    info: `Estructura Organizacional - Los Precursores de la Organización Industrial. Los Procesos Corporativos: Decisión, Planeamiento. Control. Funciones de cada área operativa de la Empresa: Comercialización; Económico Financiera; Técnico-Productiva. Compras. Ingeniería Industrial. Investigación y Desarrollo (I+D). Control de Calidad. Higiene y Seguridad Laboral. La Gerencia, Responsabilidad social empresaria. Riesgos Laborales y su prevención. Seguridad en el trabajo. Higiene en el Trabajo. Seguridad Ambiental, Normativa y Legislación. Liderazgo.`,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  // Materias equivalentes Tecnicatura -> Licenciatura
  {
    id: 90,
    name: "Matemática para Informática I",
    info: "Lógica proposicional. Argumentos y proposiciones lógicas. Conectores lógicos. Proposiciones compuestas. Tautologías, contingencias y contradicciones. Equivalencias lógicas y su utilización. Aplicación: circuitos lógicos. Argumentos válidos y no válidos. Lógica de primer orden. Componentes sintácticos del cálculo de predicados. Interpretaciones y validez. Teoría básica de conjuntos.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 91,
    name: "Introducción a Lógica y Problemas Computacionales",
    info: "Qué es la informática: hardware vs. software, historia de las computadoras, presente, posi-bles escenarios futuros. Historia del software y los lenguajes de programación: qué son los paradigmas de programación: imperativo, orientado a objeto y funcional. Lógica proposicional. Razonamientos: premisas y conclusión. Representación formal de un razonamiento.Qué es un programa. Entornos de desarrollo y ejecución. Principios de la programación imperativa: comandos (acciones). Sensores. Estructuras de control de flujo de programas (secuencia, repetición simple, repetición condicional, alternativa condicional en comandos).División en subtareas como metodología para la resolución de problemas complejos, y necesidad de dar estructura a un programa no trivial.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 92,
    name: "Organización de Computadoras I",
    info: "Historia de la computación. Definición de computadora. Magnitudes analógicas y cantidades discretas y su representación binarios en el computador. Sistemas de representación numérica (SRN) decimales y binarios. SRN posicionales en otras bases. Representación de enteros y racionales. Punto fijo y punto flotante. Errores de representación. Sistemas de representación alfanumérica. Representación de variables lógicas. Aritmética binaria. Lógica digital: Axiomas de Huntington y propiedades del algebra de Boole. Operaciones y compuertas lógicas. Circuitos combinacionales. Tabla de verdad y funciones canónicas. Semisumador y sumador. Flags. Unidades funcionales básicas del computador: ALU, registros, bancos de registros, memoria y dispositivos de entrada/salida. Buses de datos, direcciones y control. Conceptos de lenguaje de máquina y ensamblador. Código fuente y código objeto. Ensambladores, intérpretes y compiladores. Las unidades funcionales en microprocesadores, microcontroladores y sistemas embebidos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 93,
    name: "Programación Estructurada",
    info: "Valores y expresiones, tipos, estado. Terminación y parcialidad. Precondiciones como metodología para desarrollo de software robusto. Principios de la programación estructurada: funciones y procedimientos. Necesidad de darle una estructura a un programa no trivial. Resolución de pequeños problemas mediante programas. Tipos de datos estructurados, variantes y registros.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 94,
    name: "Matemática para Informática II",
    info: "Lógica de primer orden. Relaciones binarias: relaciones de orden, relaciones de equivalencia, relaciones funcionales. Propiedades. Relaciones de orden amplio y estricto. Diagrama de Hasse. Principio de Inducción. Elementos básicos de análisis combinatorio.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 95,
    name: "Organización de computadoras II",
    info: "Representación de la información. Algebra de Boole. Circuitos digitales. Combinacionales genéricos. Circuitos combinacionales específicos: Sumador, decodificador, multiplexor, demultiplexor, detector de paridad, comparador de magnitud y codificador de prioridades. Circuitos secuenciales. Celda de memoria, registro de desplazamiento y contador. Organización y arquitectura del computador. Las unidades funcionales. Unidad aritmético lógica (ALU). Memoria y sus niveles de jerarquía. Unidad de control y camino de datos. Subsistemas de entrada y salida. ISA. Instrucciones en código de máquina. Von Neumann. Harvard. RISC. CISC. Ciclos de instrucción. Tipos de direccionamiento. Lenguaje de transferencia de registros (RTL). Código fuente y código objeto.Ensambladores, intérpretes y compiladores. Conceptos de arquitecturas superescalares y multiprocesamiento.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },

  // Materias UNAHUR
  {
    id: 100,
    name: "Literatura Argentina y Latinoamericana",
    info: "Desafíos para la percepción en el “nuevo” continente. Las crónicas de Indias. El barroco como el estilo de las primeras escrituras nativas. Los usos políticos de la literatura. El escritor como hombre de Estado. Contradicciones y apuestas estéticas y políticas en los procesos de formación de los estados americanos. Civilización y barbarie como conceptos operativos para la intervención en política. Las sociedades latinoamericanas, entre la tradición y la modernidad. Localismo y cosmopolitismo. Apropiaciones y modificaciones de estilos tradicionales latinoamericanos y de la cultura universal. La experiencia de la vanguardia en América Latina. Los excluidos y los perseguidos en el siglo XX. En Argentina, el peronismo y los peronistas como protagonistas centrales. En México, los efectos de la Revolución Mexicana. En Chile, la dictadura pinochetista. Estrategias estéticas para dar cuenta de la persecución política. Periodismo y mirada social. Los géneros discursivos y la multiplicidad de errores. Latinoamérica en los años recientes. Nuevas literaturas para las aperturas democráticas. Jóvenes, política y nuevos modos de circulación de la literatura.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 101,
    name: "Historia del Pensamiento Científico y el Desarrollo Tecnológico",
    info: "Ciencia antigua. Introducción a la ciencia antigua. Desarrollo de la matemática y la geometría. Ciencia medieval. Ciencia moderna. El método hipotético deductivo. El método inductivo. El método experimental. Ciencia contemporánea. Ciencia en el siglo XX. Problemas complementarios. Ciencia y ética. Ciencia y religión. Origen del universo: Big Bang. Física nuclear, armas nucleares y guerra fría. Tratado de no proliferación de armas nucleares. Posición argentina y latinoamericana.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 102,
    name: "Ficciones de la patria",
    info: "El nacimiento de la literatura argentina. La independencia y las guerras civiles. Unitarios y federales a través de la literatura. Realis<mo, romanticismo y gótico: el género como elabo-ración de conflictos sociales. La función práctica de la literatura. La gauchesca y los albores del Estado nación. Del Centenario a la 'Década Infame': orden lingüístico y orden social. El problema de la lengua nacional. Campo intelectual y profesionalización del escritor. Las dos tradiciones de la literatura argentina desde la perspectiva del uso del lenguaje. El Estado peronista y la literatura argentina: la circulación de mitos, ficciones y relatos. Los intelectuales ante el peronismo: modos de réplica en la literatura argentina. Los años 70 y el compromiso del escritor. ¿Cómo narrar el horror? La 'herencia cultural del Proceso' en el análisis de Fogwill. La poesía argentina de los años 90 ante la debacle de 'los grandes relatos'. Cultura joven, consumo y mercado. Neoliberalismo y descomposición social. Objetivismo y habla cotidiana.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 103,
    name: "Innovacion y creatividad",
    info: "Creatividad, avance e innovación. Ciencia y tecnología. Fábricas de tecnología. Categorías de innovación. Incidencia macroeconómica. La innovación y desarrollo en las empresas, su fundamento económico. El cerebro y la mente consciente e inconsciente. Desarrollo cerebral. Los hemisferios. La percepción. La intuición. Desarrollo emprendedor. Conceptos. Desarrollo y gestión de oportunidades. Planes de negocio. Técnicas de creatividad. La no creatividad. Técnicas de pensamiento. Técnicas divergentes. El pensamiento lateral, movilización mental y técnicas convergentes. Aspectos emocionales. Trabajo en grupo. Negociaciones",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 104,
    name: "Problemas de la Filosofía",
    info: "Los orígenes de la filosofía. Grecia y el origen de la filosofía. Orígenes existenciales de la filosofía. La filosofía entre el arte y la ciencia. La duda radical. Definiciones críticas de filosofía. El poder. El poder en las concepciones pre modernas. El quiebre contractualista. Foucault y el panoptismo: el funcionamento automático del poder. El poder y el discurso. Posmodernidad y sociedad del espectáculo. La crisis de la modernidad y el fin de los grandes relatos. Pos modernidad y pos verdad. Sociedad de la comunicación, sociedad del consumo, sociedad del espectáculo. El otro. El lugar del otro en la filosofía occidental. La violencia y el otro. La idea de libertad y la ética de la responsabilidad. El extranjero. Salir del yo.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 105,
    name: "Abordaje de situaciones sociales complejas",
    info: "Paradigma de la complejidad de Edgar Morin y síntesis filosófica de Francisco Leocata. Las redes sociales, el vínculo de la persona con la comunidad y la exclusión. El paradigma de la complejidad. La antropología cristiana. Conceptualización del problema de la droga. Los distintos modelos asistenciales. Los principios de la Doctrina Social de la Iglesia y el Magisterio del Papa Francisco como marco político. Las redes como respuesta a la complejidad.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 106,
    name: "Arte contemporáneo argentino y latinoamericano",
    info: "Los artistas y sus obras más destacadas del siglo XX y XXI en el Arte contemporáneo argentino y latinoamericano. La vanguardia en Latinoamérica, las nuevas técnicas artísticas y los significados del arte. En Argentina siglo XIX: los pintores de la Generación del 80, realismo e historicismo. Siglo XX: La vanguardia como fenómeno social y estético.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 107,
    name: "Arte y tecnología. Escuela de espectadores",
    info: "La mirada del espectador. Exploración de las múltiples conexiones que existen entre la literatura, el cine, el teatro y las artes plásticas y su relación con la tecnología. Artes plásticas. Lengua y literatura. Teatro y representación. Cine y tecnología. Fotografía.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 108,
    name: "Astro: Relación de la Humanidad con el Cosmos",
    info: "Temas y problemas de Astronomía, en una visión general, contextual e histórica. La Astronomía en la Antigüedad. La Esfera Celeste. Elementos de sistemas de coordenadas esféricos. El Tiempo Astronómico. Sistema Solar. Elementos de Astrofísica. Estrellas. Sistemas Estelares. Elementos de Cosmología. Nuevos mundos: Sistemas Extrasolares.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 109,
    name: "Cine documental. Miradas desde el Sur",
    info: "Los profundos cambios a nivel social que se han producido en el mundo contemporáneo y más específicamente en la argentina durante las últimas dos décadas nos dan el marco para poder pensar como el cine documental ha tratado y representado esos acontecimientos. Las vivencias en los cambios individuales y colectivos en perspectiva de derechos humanos, de género, de nuevos hábitos y costumbres en torno al trabajo, la familia, la convivencia entre generaciones las rupturas y los nuevos acuerdos que se producen entre jóvenes y adultos en relación con la forma de entender el mundo contemporáneo. Las implicancias de una posible pedagogía de la mirada partiendo de la necesidad de trabajar los temas complejos que cruzan la vida cotidiana hoy.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 110,
    name: "Ciudadanía activa y compromiso social",
    info: "Las políticas de infancias, el rol del Estado y las nuevas prioridades de agenda en derechos de la niñez y en la reducción de las desigualdades en la Argentina y en el contexto latinoamericano.Las políticas sociales de infancias, la igualdad de oportunidades y de resultados; los paradigmas de políticas de infancia y adolescencia en Argentina y América Latina; la desigualdad y la pobreza en la infancia y adolescencia; la inversión social.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 111,
    name: "Cuando los Pasados No Pasan: lugares de memoria",
    info: "La memoria. La noción de 'lugares de memoria'. Genocidios del siglo XX: un acercamiento histórico y conceptual. El terrorismo de Estado en Argentina. Políticas de memoria: derechos humanos ayer y hoy. El memorial de Berlín; la historia de vida de Soghomon Tehlirian; la fecha del 24 de marzo; el pañuelo de las Madres; el Himno Nacional Argentino o el Museo/sitio de memoria ESMA pensados críticamente para conocer el pasado y construir una economía general del pasado en el presente.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 112,
    name: "Ciencias en la cocina",
    info: "Nociones básicas de la química de los alimentos. Calor y temperatura.Entropía y difusión. Física del estado sólido. Reacción de Maillard. Confección de informes delaboratorio",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 113,
    name: "Educación Sexual Integral. Cuando lo esencial es visible a los ojos",
    info: "Introducción a la Educación sexual integral: enfoques y tradiciones de la educación sexual. El paradigma de derechos como marco para las prácticas pedagógicas de ESI: Declaración de los Derechos Humanos y otras leyes que cambiaron paradigmas. La Ley Nacional N°26.150/06. Nueva/os sujetos: niñez y adolescencia; autonomía progresiva; superación del paradigma tutelar. Educación Sexual Integral con perspectiva de género. Géneros y diversidades. El cuerpo como construcción política.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 114,
    name: "Género y sociedad: una nueva mirada para una era más justa",
    info: "El concepto de género: definiciones, argumentos y debates. La lógica binaria en los discursos culturales. Mujeres y trabajo. Relaciones entre identidad, trabajo y género. La categoría de cuidado. El sistema patriarcal. Estructura-individuo. Las relaciones sexuales como relaciones políticas de dominio de los hombres sobre las mujeres. El feminismo de la igualdad y el feminismo de la diferencia. 'Lo natural' y 'La norma'. Educación desde una perspectiva de género. La escuela y el currículum como espacios de producción de subjetividades. Debates contemporáneos en torno a la pedagogía, los géneros y las sexualidades. Tecnologías corporales, saberes biomédicos y normalización. Aportes de la teoría queer para pensar las diferencias.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 115,
    name: "Introducción a la Imagen. De la imagen fija a la imagen en movimiento",
    info: "Enfoque semiótico y giro pictórico. El problema de la representación. La imagen como signo. La relación entre el significado y el referente. El lenguaje de los nuevos medios. La cultura visual y el estudio de la visualidad. La imagen mediática. La retórica de la imagen. El acto fotográfico. La potencia política de las imágenes. Collage y montaje. El lugar del espectador emancipado. Herramientas del lenguaje visual. Artes y medios visuales y audiovisuales. La estética de lo performativo y la teatralidad.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 116,
    name: "Introducción a la lengua latina",
    info: "Abordaje de la morfosintaxis latina: oraciones originales o adaptadas que empleen un vocabulario específico, reflexión sobre la gramática latina. Notaciones generales e introductorias acerca de los roles asignados en las distintas textualidades de la cultura antigua para la mujer. Abordaje de textos de la oratoria ciceroniana, la poesía lírica de Catulo, Ovidio, Propercio, y la sátira Horaciana y de Juvenal.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 117,
    name: "Introducción al griego antiguo",
    info: "Los temas principales que constituyen el contenido de la asignatura son el estudio de la historia de la lengua griega y su escritura, la morfología nominal y verbal, y la sintaxis.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 118,
    name: "La vida secreta de las rocas",
    info: "Introducción a la geología: origen y evolución del universo, el Sistema Solar y la Tierra. El tiempo geológico. Introducción a la paleontología: evolución e historia de la vida en la Tierra. Registro geológico. Cambio climático. Mineralogía: propiedades de los minerales. Métodos de identificación de minerales. Introducción a la sistemática mineral. El ciclo de las rocas: Procesos endógenos y exógenos. Geología e hidrocarburos: Sistema petrolero convencional y no convencional. Importancia estratégica e implicancias ambientales de las actividades.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 119,
    name: "Literatura y Memoria",
    info: "Literatura y testimonio. El testimonio como resistencia. El testimonio como género literario. Testimonio, verdad y hechos históricos. Los artificios del arte. Jorge Semprún: ¿Cómo contar lo invivible? Memoria testimonial / Memoria ejemplar. Memoria / Historia. Ética y Memoria. Un posible modo de narrar lo invivible: la experiencia de haber muerto. La ficción de la memoria. La novela de ficción y la ciencia ficción como otras posibles respuestas a cómo contar la tragedia social. Los materiales autobiográficos. La verdad como imposible y como motor para escribir en su búsqueda sin cesar. Las ficciones autobiográficas argentinas. Las infancias como insumo de la memoria y la imaginación. La experiencia propia que resuena en la experiencia social.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 120,
    name: "Literatura y Política",
    info: "Relación entre literatura y política. El modo en que grandes acontecimientos del siglo XX impactaron en la literatura de América Latina y, viceversa, el modo en que la literatura latinoamericana impactó sobre su contexto. Poesía política latinoamericana. El retroceso de las utopías y la irrupción de las dictaduras. El neoliberalismo en Argentina. El impacto del peronismo en los intelectuales argentinos. Del antiperonismo a la Revolución Cubana. Alegoría, símbolo y lenguaje cifrado. El cuento como 'respuesta' a la coyuntura política. Las letras de rock como literatura. Neoliberalismo, superficialidad y exclusión social en las letras.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 121,
    name: "Mal de tango. La historia argentina a través del tango",
    info: "El nacimiento del tango. Las discontinuidades entre el tango de los comienzos, el tango canción y el tango de vanguardia. La relación entre la historia del tango y la historia de argentina moderna. Eltango canción y los efectos en la ley 1420 de educación. Moral y patriotismo. El período de oro deltango y su relación con el peronismo. Piazzolla y el otro registro del tango.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 122,
    name: "Malvinas: una Causa de nuestra América Latina",
    info: "Los principales argumentos históricos. Descubrimiento, colonización y usurpación. Los argumentos jurídicos: de la usurpación a las Naciones Unidas. Malvinas como causa política de Estado. Integridad territorial y Libre determinación de los pueblos. Otros casos de colonialismo bajo la bandera de la libre determinación. El Atlántico Sur en la geopolítica de América Latina: recursos naturales, depredación y militarización. Soberanía sobre el Atlántico Sur. La Antártida como espacio de disputa.Historia contemporánea de la causa Malvinas: guerra y posguerra. Inglaterra y los problemas de financiamiento de las islas. Intercambios en materia de comunicación, recursos energéticos y educación. El golpe cívico militar de 1976 y el cambio de perspectiva. La decisión de tomar Malvinas y la derrota. Los ochenta y los noventa: la 'desmalvinización'. Posneoliberalismo y remalvinización. Malvinas como causa regional. Un nuevo período de desmalvinización.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 123,
    name: "Manipulacion genética en humanos. Historia, mitos y realidades",
    info: "Diversidad y desigualdad. Determinismo biológico en el siglo XIX: frenología, craneometría, antropología criminal, tests de CI. Evolucionismo sociológico y antropológico. Evolucionismos biológicos: teoría darwiniana, embriología, ontogenia y filogenia. El movimiento eugenésico. Tecnologías biomédicas y sociales. El debate ético, político y filosófico en torno a la eugenesia liberal. Tecnología y biopolítica: diversidad y desigualdad. La ética eugenista; Sano/enfermo: medicalización. El diagnóstico preimplantatorio, el CRISPR y otras tecnologías de reproducción humana.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 124,
    name: "Métodos participativos de transformación de conflictos",
    info: "El diálogo colaborativo y la construcción de consensos. Convivencia ambiental. Teoría del Conflicto. Su apreciación y tratamiento como oportunidad de cambio. Comunicación. Conocimientos básicos y aplicación a la vida comunitaria y profesional. Negociación. Técnicas y herramientas. Mediación. Procesos de mediación y su incidencia en la cultura. Facilitación en procesos de abordaje de conflictos intra e inter institucionales. Procesos participativos de prevención temprana y adecuado abordaje de conflictos comunitarios.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 125,
    name: "Modos de ver el Mundo contemporáneo a través del lenguaje audiovisual",
    info: "Los cambios profundos que se han producido en el mundo del trabajo durante los últimos años en las formas de organizar el ciclo laboral y las condiciones laborales como factores de cambios culturales e identitarios. Las vivencias de los cambios individuales y colectivos de los 'nuevos' trabajadores que se incorporan hoy en el mercado laboral. Rupturas generacionales que se producen entre jóvenes y adultos en relación con la forma de entender el trabajo. La representación del mundo laboral en el lenguaje audiovisual de las últimas décadas. Forma de influencia de los medios audiovisuales en la percepción del espectador acerca del empleo. Debates sobre las implicancias de una posible pedagogía de la mirada partiendo de la necesidad de trabajar los temas complejos que cruzan la vida cotidiana hoy.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 126,
    name: "No sos vos, es Freud: una introducción al psicoanálisis",
    info: "El surgimiento del psicoanálisis en la historia de occidente y los efectos de su invención en las ciencias del sujeto. El descubrimiento de inconsciente como 'saber no sabido' en los actos fallidos y los sueños. La ampliación del concepto de sexualidad, el lugar del amor en el vínculo psicoanalítico y la relación de poder.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 127,
    name: "Nosotrxs y los otrxs. Hacia una práctica profesional inclusiva",
    info: "Los derechos humanos en la historia. Las cuatro generaciones de derechos. Conceptos de igualdad, equidad, discriminación y tolerancia. Racismo y nuevas xenofobias. Poblaciones marginadas,sujetos de derechos. Estrategias de inclusión para la práctica profesional.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 128,
    name: "Pensamiento Ambiental Latinoamericano",
    info: "Introducción al pensamiento ambiental latinoamericano (PAL). La educación y el desarrollo como dos ejes y preocupaciones centrales del PAL. El rol de la educación superior: avances y desafíos. Las concepciones del desarrollo que se disputan al Norte global. La incorporación de la dimensión ambiental en la educación superior. De la EA a la Educación para el Desarrollo Sustentable: un desplazamiento que no sólo es conceptual sino político. El post- desarrollo como alternativa al desarrollo. La ecología política y la propuesta de decolonizar la naturaleza.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 129,
    name: "Pensamiento Nacional",
    info: "Las cosmovisiones en pugna sobre la conquista de América. Una dualidad transhistórica: civilización y barbarie. El concepto de matriz autónoma de pensamiento popular latinoamericano. La conformación del Estado Nacional. Ley 1420. Los gobiernos populares del siglo XX. El carácter fundacional de la Fuerza de Orientación Radical de la Joven Argentina (FORJA). Los imprescindibles: J. J. Hernández Arregui; R. Scalabrini Ortiz. A.Jauretche La cultura popular. E. S. Discépolo. Los medios masivos de comunicación y la construcción de la realidad. La lucha de los postergados: movimientos de mujeres y de poblaciones originarias.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 130,
    name: "Pensar Hurlingham",
    info: "El gobierno local. Los municipios argentinos, una primera aproximación. Nuevas incumbencias, viejas competencias, débiles capacidades estatales. La descentralización y desconcentración municipal. Los servicios públicos municipales. Los servicios urbanos y el hábitat. Región metropolitana y Conurbano bonaerense. La Nueva cuestión social. El Estado de Bienestar. Pobreza y desigualdad. El conurbano. Conceptos fundamentales del desarrollo local. El debate del desarrollo: La matriz moderna del desarrollo. Los pilares políticos y epistemológicos del desarrollo. La visión del desarrollo humano y sustentable. El concepto de territorio local en el desarrollo endógeno. Planificación y ordenamiento territorial. Las políticas públicas locales. Qué son las políticas públicas. La discusión entre políticas públicas universales y focalizadas. La discusión en torno a los derechos y a su ejercicio. El ciclo de las políticas públicas.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 131,
    name: "Repensar la discapacidad: yo estoy al derecho, dado vuelta estás vos",
    info: "Revisión crítica de los modos de entender y abordar la discapacidad a nivel social, las representaciones sociales y los modos de nombrarlas. Historización de los diferentes modos deconceptualización de la discapacidad: modelo de prescindencia y modelo médico-rehabilitador.Discursos y prácticas actuales. Movimientos que dieron lugar al Modelo Social de la discapacidad.Sus postulados principales: la discapacidad como categoría social y política. La construccióndiscursiva de la normalidad: diversidad y alteridad. El concepto de discapacidad como unacategoría de análisis transversal a las disciplinas. La producción colaborativa de accesibilidad.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },

  {
    id: 132,
    name: "Robótica",
    info: "Tecnología y sociedad. Antecedentes históricos y modificaciones para construir autómatas y androides. Definiciones de robótica, mecatrónica y otras asociadas. Disciplinas científicas de esta área de conocimiento. Clasificación de robots en distintas categorías. Partes que componen un dispositivo robótico. Software libre y de código abierto. Tipo de Licencias. La robótica en la actualidad. Aspectos éticos y sociales de la robótica. Introducción a la programación. Interpretación de enunciados y requerimientos. Modelización de forma abstracta de problemas concretos. Pensamiento lógico matemático.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 133,
    name: "Técnicas de investigación en opinión pública",
    info: "Fundamentos de la investigación en Ciencias sociales. Paradigmas: diversidad y coexistencia. El papel de la teoría en el proceso de investigación social. Métodos, objetivos, planteo del problema e hipótesis en la redacción de un proyecto de investigación. Diseño de investigación: conceptos, empiria y decisiones. Tipos de estudios y datos. Herramientas metodológicas y técnicas. Conceptualización y operacionalización. Universo de análisis y muestras. Metodología, métodos y técnicas. Metodología cuantitativa y cualitativa. El trabajo de campo. Investigación social orientada. Alcances y limitaciones del análisis estadístico. Contacto, aceptación de la entrevista y respuesta. Procesamiento. Análisis. Fundamentos del análisis.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 134,
    name: "Una Historia del Rock Nacional",
    info: "Los orígenes del Rock Nacional. Las derivas urbanas como método compositivo. El núcleo fundador. Espacios de sociabilidad. La jerga del rock. Rock y marginalidad. El Cordobazo. La década del 70. Inspiraciones bajo el látigo de la violencia. El apogeo del Rock Nacional. Concepto de 'música progresiva'. Folklore y rock. El rock sinfónico. La década del 80. Modernidad o muerte. La guerra de Malvinas como separatoria de aguas. La recuperación democrática. La rebelión punk. De los teatros y estadios al pub y los lugares emblemáticos. El canto popular urbano. La década del 90. La balsa a la deriva. La canción neoliberal. Año 2000 y después. La vuelta de Boedo y Florida: la movida sónica y el rock chabón. Las tribus urbanas. Experimentación y poesía social. Cumbia y protesta social. Últimos años: La producción independiente y las nuevas tecnologías. La muerte del disco.",
    infoUrl: null,
    area: "UNAHUR",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },

  {
    id: 200,
    name: "Complementaria",
    info: "Materia complementaria Tecnicatura en informatica.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  // Tecnicatura en programación

  {
    id: 300,
    name: "Taller de Lenguajes de Marcado y Tecnologías Web",
    info: "Conceptos de lenguaje de marcado. Markdown y sistemas de marcado simples, como forma de redactar información con contenido semántico. Lenguajes de marcado basados en etiquetas: XML, HTML. HTML como definición de páginas web. Etiquetas semánticas de HTML5. CSS como forma de dar estilos a sitios web. Tecnologías de generación estática y dinámica de contenidos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 301,
    name: "Electiva I (Programación)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Programación.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 302,
    name: "Electiva II (Programación)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Programación.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },

  // Tecnicatura en Redes
  {
    id: 400,
    name: "Taller de intérpretes de comandos",
    info: "Interfaz operativas de usuario, GUIs vs CLIs. Sistemas CLIs en Linux. Formato de comandos: argumentos, flags. Comandos comunes. Directorios, rutas absolutas y relativas. Gestionar archivos con CLI.. Su y sudo. Piping y redireccionado. Búsquedas. Acciones por lotes. Concepto de variables de entorno y archivos de configuración. Creación de scripts para la automatización de procesos complejos. Scripting simple con Bash.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  {
    id: 401,
    name: "Sistemas de comunicación",
    info: "Informática y comunicaciones. Distintos Sistemas de Comunicaciones. Transmisión Analógica y Digital Conceptos básicos de ruido, distorsión y ancho de banda. Medidas usadas en telecomunicaciones Tipos de transmisión. Canales de comunicaciones Arquitectura de comunicaciones. Modelo de capas Modulación y multiplexación. Medios físicos de comunicación. Clasificación de redes: alámbricas, inalámbricas, fibra. Redes WAN y LAN. Familias de protocolos. La capa de transporte.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 402,
    name: "Operaciones I",
    info: "Introducción a operaciones en los contextos de las tecnologías de la información (IT). Ambientes. Sistemas de producción. Conceptos de despliegue e integración. Despliegue continuo. Buenas prácticas, gestión del proyecto. Herramientas. Métricas.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 403,
    name: "Redes avanzadas",
    info: "Protocolo IPv6 - Sistemas Autónomos / ISPs / NAPs - Ruteo Interno y Externo en sistemas autónomos. Características de los ISPs (proveedores de servicios de Internet). Servicios distribuidos. Seguridad en Redes de Computadoras y Dispositivos. Optimizaciones de ruteo y servicios. Redes basadas en software. Virtualización de redes. Redes IOT.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 404,
    name: "Electiva I (Redes)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Redes.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 405,
    name: "Electiva II (Redes)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Redes.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 406,
    name: "Operaciones II",
    info: "Operaciones y modelos de gestión ágiles. Fundamentos de integración y despliegues continuos. Infraestructura de nube. Herramientas. Arquitecturas de contenedores (Docker, otras). Automatizaciones. Trabajo con contenedores. Contenedores y nube. El Software como Servicio. Alternativas abiertas para servicios en la nube. Monitoreo.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },

  // === Tecnicatura en Inteligencia Artificial (ID carrera 5) ===
  {
    id: 500,
    name: "Introducción a la inteligencia artificial",
    info: "Qué es la inteligencia artificial (IA), historia, evolución. Definiciones y enfoques y propósitos. Paradigmas de la IA: conexionista, clásico. Problemas de IA. Dominios: técnicos, formales, cognitivos. Cuestiones éticas y sociales. Sesgos algorítmicos. Impacto del uso de la IA. Definiciones de principios éticos. Regulaciones nacionales e internacionales. Posicionamiento de los/las profesionales en la resolución de problemas mediante IA.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 501,
    name: "Álgebra lineal",
    info: "Matrices y sus operaciones. Inversa de una matriz cuadrada. Sistemas de Ecuaciones Lineales. Función Determinante. Métodos de solución de un sistema de ecuaciones lineales: Gauss-Jordan y Cramer. Sistemas de ecuaciones lineales homogéneos. Espacios vectoriales. Subespacios vectoriales. Combinación lineal y espacios generados. Independencia lineal. Base y dimensión de un espacio vectorial. Espacios vectoriales genéricos. Cambio de bases. Transformaciones lineales. Matriz de una transformación lineal. Autovalores y autovectores. Diagonalización de matrices.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 502,
    name: "Cálculo",
    info: "Funciones. Representación gráfica. Dominio e Imagen. Funciones polinomiales, racionales, exponenciales, logarítmicas, trigonométricas. Función inversa. Composición de funciones. Límite. Continuidad. Derivada. Aplicaciones del teorema del valor medio. Regla de L'Hôpital. Estudio completo de funciones. Optimización de problemas.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 503,
    name: "Taller de Programación I",
    info: "Valores y expresiones, tipos, estado. Terminación y parcialidad. Precondiciones como metodología para desarrollo de software robusto. Principios de la programación estructurada: funciones y procedimientos. Necesidad de darle una estructura a un programa no trivial. Resolución de pequeños problemas mediante programas. Tipos de datos estructurados, variantes y registros. Herramientas y lenguajes para el procesamiento de datos. Entornos integrados de desarrollo.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 504,
    name: "Taller de Programación II",
    info: "Programas recursivos. Representación de datos en memoria. Paso de variables por valor y por referencia. Tipos abstractos de datos. Estructuras de datos. Estructuras contenedoras: Vectores, matrices, pilas, colas, lista, diccionarios, árboles y grafos. Implementación de estructuras de datos estáticas. Uso dinámico de memoria. Listas y árboles implementados con punteros. Análisis, eficiencia e implementación de estructuras de datos. Algoritmos de recorrido, búsqueda y ordenamiento. Nociones básicas de algoritmos sobre grafos. Conceptos básicos de Programación Orientada a Objetos: objeto y mensaje. Testeo automático y repetible. Nociones básicas sobre manejo de errores. Interrupción del flujo de ejecución: modelado mediante estructuras de control, concepto de excepción.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 506,
    name: "Fundamentos de redes neuronales",
    info: "Introducción. Origen, historia y fundamentos biológicos. Funcionamiento de las redes neuronales artificiales. Problemas que pueden resolver. Modelos. Componentes. Funciones de activación. Red neuronal artificial (RNA). Arquitectura de las RNA. Aprendizaje. Perceptrón simple y multicapa. Descenso de gradiente. Algoritmos de propagación.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 507,
    name: "Fundamentos de ciencias de datos",
    info: "Aplicaciones de la ciencia de datos. Flujos de trabajo. Tipos de datos en ciencia de datos. Herramientas. Series de datos. Dataframes. Manipulación y combinación. Vistas, selección, limpieza de datos. Operaciones escalares y vectoriales. Análisis exploratorio de datos: ploteo y gráficos.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 3,
    hsTotal: 48,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 508,
    name: "Aprendizaje automático",
    info: "Aprendizaje, inferencia y predicción. Tipos de problemas que resuelve el aprendizaje automático (AP). Métricas de evaluación: precisión, accuracy, recall. F1-score. Matriz de confusión. Aprendizaje supervisado. Clasificadores. Árboles de decisión. Máquinas con vectores soporte. Regresión lineal, múltiple y logística.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  {
    id: 509,
    name: "Electiva I (IA)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en IA.",
    infoUrl: null,
    area: "Específica",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 510,
    name: "Taller de Programación III",
    info: "Algoritmos de búsqueda. Heurísticas. Diferentes tipos de búsqueda. Eficiencia algorítmica. Optimización de algoritmos. Programación de unidades de procesamiento gráfico (GPU). Diferencias con CPU. Programación en paralelo. Estándares abiertos (OpenCL, OpenACC). Opciones propietarias. Librerías específicas.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 511,
    name: "Aprendizaje automático avanzado",
    info: "Aprendizaje no supervisado. Clustering. Componentes principales. Aprendizaje profundo. Codificadores y decodificadores. Auto-codificadores. Autocodificadores-variacionales. Redes convolucionales. Redes generativas antagónicas (GAN). Transformers y attentions. Arquitectura. Entrada, salida. Tipos. Variantes. Aplicaciones en tratamento de textos, imágenes, lenguaje natural, audio.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 512,
    name: "Procesamiento de imágenes y visión por computadora",
    info: "Representación de imágenes en forma digital. Captura de imágenes. Parámetros, sensores. Modos de color. Manipulación de imágenes. Operaciones. Filtros. Transformaciones. Detección, clasificación y segmentación. Extracción de características. Reconocimiento de objetos. Uso de conjuntos de datos (datasets). Aprendizaje profundo aplicado a imágenes.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 513,
    name: "Proyecto integrador",
    info: "Trabajo en equipo. Definición de objetivos. Planificación y gestión de recursos informáticos. Metodología de trabajo en equipo. Selección de fuentes de datos, tratamiento y preparación. Elaboración de Informes. Herramientas de colaboración y comunicación. Implementación de un modelo para un caso real. Exposición final.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },

  // Tecnicatura en Videojuegos
  {
    id: 600,
    name: "Introducción a los videojuegos",
    info: "Historia de los videojuegos. Géneros de Videojuegos. Videojuegos en Argentina y en América Latina. Plataformas. Equipo Técnico. Colaboración Interdisciplinaria. Desarrollo Creativo.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 601,
    name: "Taller de diseño conceptual de juegos",
    info: "Introducción al Diseño de Juegos. Mecánicas. Dinámicas. Estéticas. Diseño orientado al usuario. Narrativas. Documentación: High Concept, GDD. Diseños de prototipos. Prototipado en papel. Herramientas de prototipado digital. Técnicas de iteración.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 602,
    name: "Arte digital para videojuegos",
    info: "Representación de la imagen bidimensional y tridimensional. Storyboards. Estilos de animación: tradicional / stop motion / recortables. Escala de tiempo. Diseño digital. Estilos. Software de diseño. Resolución. Perfiles de color. Capas de trabajo. Entintado Digital. Efectos. Exportación de proyectos. Sprite sheets. Tiles.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 603,
    name: "Introducción a motores de videojuegos",
    info: "Relevamiento de Motores de videojuegos (Game Engine). Programación y conceptos del motor. Colisiones. Rozamiento. Arreglos. Clases. Relación entre clases. Instancias. Sistemas de entrada. Periféricos de jugabilidad. Herramientas de exportación. Prototipado y testing.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 604,
    name: "Programación de videojuegos I",
    info: "Aproximación al diseño de software. Noción de decisión de diseño, el diseño como proceso de toma de decisiones. Conceptos de acoplamiento y cohesión. Problemas que derivan de un grado de acoplamiento inadecuado. Vinculación entre las ideas básicas de diseño y el paradigma de objetos. Características deseadas en un diseño de objetos. Patrones de diseño. Nociones sobre proceso de diseño. Metaprogramación. Uso de un entorno integrado de software. Notación UML de los diagramas de clases, de objetos y de secuencia. Testeo unitario y automático. Manejo de errores, impacto del manejo de errores en el diseño. Exportación de proyectos. Plataformas de publicación.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 605,
    name: "Electiva I (Videojuegos)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Videojuegos.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 606,
    name: "Electiva II (Videojuegos)",
    info: "Materia electiva del plan de estudios de la Tecnicatura en Videojuegos.",
    infoUrl: null,
    area: "Electiva",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 607,
    name: "Programación de videojuegos II",
    info: "Videojuegos multijugador. Hot Seat. Simultáneo. Pantalla dividida. Red Local. On line. Massive On line. Redes de información. Videojuegos multijugador por turno y en tiempo real (diferencias e igualdades). Arquitectura cliente-servidor y peer-to-peer. Sincronización.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
];
