export const coursesSeed = [
  {
    id: 1,
    name: "Matemática I",
    info: "Elementos de lógica proposicional: conectivos lógicos (negación, conjunción, disyunción, implicación, bicondicional), tablas de verdad, equivalencias lógicas y leyes de De Morgan. Lógica de predicados: cuantificadores universal y existencial, negación de cuantificadores, ejemplos de formalización de enunciados. Teoría básica de conjuntos: definición de conjunto, operaciones (unión, intersección, diferencia, complemento), producto cartesiano, relaciones binarias (reflexivas, simétricas, transitivas), relaciones de equivalencia y particiones. Funciones: definición, inyectividad, sobreyectividad, biyectividad, composición de funciones, funciones inversas. Principio de inducción matemática: demostraciones por inducción sobre números naturales, ejemplos de aplicación en sumatorias y desigualdades. Estructuras discretas: introducción a grafos (definición, tipos: dirigidos y no dirigidos, representación matricial), árboles y sus propiedades. Elementos básicos de análisis combinatorio: principio de conteo, permutaciones, combinaciones, binomial de Newton.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 2,
    name: "Introducción a la Programación",
    info: "Introducción a los conceptos fundamentales de la programación: qué es un programa, diferencias entre hardware y software, roles del programador. Entornos de desarrollo y ejecución: uso de IDEs, compiladores e intérpretes. Paradigmas de programación: descripción de los paradigmas imperativo, orientado a objetos, funcional y lógico, con ejemplos introductorios. Principios de la programación imperativa: acciones y comandos (asignación, entrada/salida), valores y expresiones (aritméticas, lógicas), tipos de datos básicos (enteros, reales, booleanos, caracteres), variables y estado del programa. Estructuras de control: secuencia, selección (if, switch), iteración (while, for). Introducción a la programación estructurada: funciones y procedimientos, paso de parámetros por valor y referencia, ámbito de variables. Resolución de problemas: metodología para descomponer problemas en subproblemas, diseño de algoritmos simples (búsqueda, ordenamiento básico). Estructuras de datos básicas: arreglos unidimensionales, registros (structs), ejemplos de uso en problemas prácticos.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 3,
    name: "Organización de Computadoras",
    info: "Conceptos básicos de la arquitectura de computadoras: modelo de Von Neumann, componentes principales (CPU, memoria, dispositivos de entrada/salida). Representación de la información: sistemas de numeración (binario, octal, hexadecimal), conversión entre bases, representación de números enteros (signo-magnitud, complemento a dos), números en punto flotante (IEEE 754), códigos alfanuméricos (ASCII, Unicode). Aritmética computacional: operaciones binarias (suma, resta, multiplicación, división), detección y corrección de errores numéricos. Lógica digital: puertas lógicas (AND, OR, NOT, NAND, NOR, XOR), tablas de verdad, diseño de circuitos combinatorios (sumadores, multiplexores), circuitos secuenciales (flip-flops, registros). Lenguaje ensamblador: estructura de instrucciones, registros, direccionamiento, ejemplos de programas simples. Organización funcional: unidad central de procesamiento (ALU, registros, unidad de control), ciclo de instrucción (fetch-decode-execute), memoria principal (RAM, ROM), jerarquía de memoria (caché, memoria virtual), subsistema de entrada/salida (interrupciones, DMA).",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 4,
    name: "Nuevos Entornos y Lenguajes",
    info: "Introducción a la producción de conocimiento en la era digital: evolución de la Web (1.0, 2.0, 3.0), características de la cultura digital, impacto de las tecnologías en la comunicación y el aprendizaje. Lectura y escritura en la nube: conceptos de hipertextualidad e hipermedialidad, uso de herramientas colaborativas (Google Docs, wikis), análisis de textos digitales. Búsqueda de información: criterios para evaluar fuentes (confiabilidad, relevancia), uso de motores de búsqueda avanzados, interpretación crítica de resultados. Escritura colaborativa: dinámicas de trabajo en equipo en entornos digitales, plataformas de edición en tiempo real. Nuevas formas de producir conocimiento: redes sociales como espacios de intercambio, comunidades de práctica virtuales, inteligencia colectiva y crowdsourcing. Lenguaje audiovisual: elementos básicos de producción (guion, edición), interpretación de narrativas audiovisuales. Narrativas transmedia: convergencia de formatos (texto, video, audio), ejemplos de storytelling multiplataforma. Convergencia tecnológica: integración de dispositivos y servicios digitales.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 5,
    name: "Estructuras de Datos",
    info: "Introducción a los tipos abstractos de datos: definición, especificación, implementación. Recursión: definición, ejemplos en listas y árboles, análisis de eficiencia. Estructuras lineales: pilas (stack), colas (queue), colas de prioridad, implementación con arreglos y listas enlazadas, operaciones (push, pop, enqueue, dequeue). Estructuras de datos dinámicas: listas enlazadas simples y dobles, nodos, punteros, inserción, eliminación y recorrido. Árboles: definición, árboles binarios, árboles de búsqueda binaria (BST), árboles balanceados (AVL), operaciones de inserción, búsqueda y eliminación. Tablas hash: funciones hash, manejo de colisiones (encadenamiento, direccionamiento abierto), análisis de rendimiento. Algoritmos asociados: recorrido de estructuras (preorden, inorden, postorden), búsqueda lineal y binaria, ordenamiento básico (burbuja, inserción, selección). Representación en memoria: modelo de memoria imperativa (stack/heap), alocación dinámica, punteros y referencias. Análisis de eficiencia: notación Big-O, comparación de estructuras en términos de tiempo y espacio.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 6,
    name: "Programación con Objetos I",
    info: "Introducción al paradigma orientado a objetos: conceptos fundamentales (objeto, mensaje, clase), diferencias con programación imperativa. Polimorfismo: definición, ventajas, ejemplos de uso en diseño de software. Encapsulamiento: atributos privados, métodos públicos, getters y setters, principios de diseño. Herencia: jerarquías de clases, herencia simple, redefinición de métodos (override), method lookup. Interfaz y protocolo: definición de interfaces, implementación en clases, contratos entre objetos. Estado en objetos: referencias entre objetos, estado interno, ciclo de vida de un objeto. Colecciones: uso de colecciones como objetos (listas, conjuntos, diccionarios), protocolo de acceso (iteración, inserción, eliminación). Diseño básico orientado a objetos: principios de responsabilidad única, delegación de tareas. Testing: introducción al testeo automático (unit testing), herramientas básicas (JUnit, pytest). Manejo de errores: excepciones, estructuras de control para interrupción de flujo, buenas prácticas en manejo de errores.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 7,
    name: "Bases de Datos",
    info: "Introducción a los sistemas de bases de datos: definición, diferencias con sistemas de archivos, ventajas y desventajas. Modelos de datos: modelo conceptual (entidad-relación: entidades, atributos, relaciones, cardinalidad), modelo lógico (relacional: tablas, claves primarias y foráneas, integridad referencial), modelo físico (almacenamiento en disco). Lenguaje SQL: sintaxis básica (CREATE, INSERT, UPDATE, DELETE, SELECT), consultas simples y con condiciones (WHERE), ordenamiento (ORDER BY), funciones de agregación (COUNT, SUM, AVG, MAX, MIN), agrupamientos (GROUP BY, HAVING). Operaciones relacionales: joins (INNER, LEFT, RIGHT, FULL), subconsultas, vistas. Diseño de bases de datos: normalización (1NF, 2NF, 3NF), desnormalización para rendimiento. Administración de bases de datos: usuarios, permisos, índices para optimización, backups y recuperación. Transacciones: propiedades ACID, demarcación (BEGIN, COMMIT, ROLLBACK), concurrencia y bloqueos.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 8,
    name: "Inglés I",
    info: "Introducción a la lectura y comprensión de textos auténticos en inglés relacionados con informática y tecnología: artículos técnicos, manuales, documentación de software. Estrategias de lectura: identificación de palabras clave, palabras transparentes (cognados), palabras repetidas, uso de índices tipográficos (títulos, subtítulos, negritas). Organización textual: identificación del tema principal, despliegue temático, párrafos de introducción y conclusión. Técnicas de lectura rápida: skimming (lectura superficial para idea general), scanning (búsqueda de información específica). Cohesión y coherencia: conectores lógicos (and, but, because, therefore), referentes contextuales (anáforas, catáforas), elipsis. Morfología: prefijos y sufijos comunes en inglés técnico (un-, re-, -tion, -able). Categorías gramaticales: sustantivos, verbos, adjetivos, adverbios. Estructura de definiciones: definición de conceptos técnicos, objetos y procesos. Uso del gerundio (-ing) y participio pasado (-ed) en descripciones técnicas. Relaciones lógicas: adición, contraste, causa-efecto, enumeración.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 9,
    name: "Matemática II",
    info: "Introducción a los espacios vectoriales: definición, subespacios, combinaciones lineales, independencia lineal, base y dimensión de un espacio vectorial. Transformaciones lineales: definición, propiedades (linealidad), núcleo e imagen, representación matricial de transformaciones, composición de transformaciones. Matrices: operaciones (suma, producto, transposición), propiedades (determinante, inversa), resolución de sistemas de ecuaciones lineales mediante eliminación gaussiana y regla de Cramer. Determinantes: definición, cálculo (método de cofactores), propiedades (efecto de operaciones elementales), aplicaciones en sistemas lineales. Espacios con producto interior: definición, norma, ortogonalidad, proyecciones ortogonales, método de cuadrados mínimos para ajuste de datos.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 10,
    name: "Programación con Objetos II",
    info: "Conceptos avanzados del paradigma orientado a objetos: herencia múltiple (simulación en lenguajes sin soporte nativo), mixins y traits como alternativas a herencia, interfaces múltiples y su implementación. Diseño orientado a objetos: principios SOLID (responsabilidad única, abierto/cerrado, sustitución de Liskov, segregación de interfaces, inversión de dependencias), patrones de diseño fundamentales (factory method, singleton, observer, adapter). Polimorfismo avanzado: polimorfismo paramétrico, uso de reflexión para inspección dinámica de objetos. Programación genérica: definición de tipos parametrizados (generics), restricciones de tipo, ventajas en reutilización y seguridad de tipos. Manejo avanzado de excepciones: jerarquía de excepciones, creación de excepciones personalizadas, propagación y captura múltiple. Colecciones avanzadas: implementación de estructuras como mapas, conjuntos y listas, iteradores y streams.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 11,
    name: "Redes de Computadoras",
    info: "Introducción a las redes de computadoras: definición, clasificación (LAN, WAN, MAN), topologías (estrella, bus, anillo). Modelos de referencia: modelo OSI (capas física, enlace, red, transporte, sesión, presentación, aplicación), modelo TCP/IP (enlace, internet, transporte, aplicación). Capa física: medios de transmisión (cables de cobre, fibra óptica, inalámbricos), señales analógicas y digitales, codificación (Manchester, NRZ). Capa de enlace: protocolos (Ethernet, PPP), control de acceso al medio (CSMA/CD, CSMA/CA), direccionamiento MAC, switches y bridges. Capa de red: direccionamiento IP (IPv4, IPv6), subnetting, enrutamiento básico (tablas de enrutamiento, RIP), protocolos (IP, ICMP). Capa de transporte: TCP (control de flujo, congestión, establecimiento de conexión), UDP (características, usos). Herramientas de diagnóstico: ping, traceroute, análisis de paquetes con Wireshark.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 12,
    name: "Sistemas Operativos",
    info: "Conceptos fundamentales de sistemas operativos: definición, funciones (gestión de recursos, abstracción de hardware), tipos (monotarea, multitarea, monousuario, multiusuario). Estructura de un SO: núcleo (kernel monolítico, microkernel), interfaces (shell, API). Gestión de procesos: estados del proceso (nuevo, listo, ejecutando, bloqueado, terminado), planificación de procesos (FIFO, SJF, Round Robin), creación y terminación de procesos (fork, exec). Concurrencia: problemas de sincronización (condición de carrera), mecanismos (semáforos, monitores, mutex), deadlocks (detección, prevención). Gestión de memoria: particionamiento, paginación, segmentación, memoria virtual (tablas de páginas, TLB). Sistemas de archivos: estructura (directorios, inodos), implementación (FAT, NTFS, ext4), operaciones (lectura, escritura, montaje). Entrada/Salida: principios de hardware (controladores, interrupciones), gestión de dispositivos (buffering, spooling).",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 13,
    name: "Programación Funcional",
    info: "Introducción al paradigma funcional: principios básicos (funciones puras, inmutabilidad, ausencia de efectos secundarios), diferencias con paradigmas imperativos y orientados a objetos. Evaluación de expresiones: evaluación estricta vs. perezosa (lazy evaluation), ventajas y ejemplos en lenguajes como Haskell. Funciones de orden superior: definición, aplicación (map, filter, reduce), composición de funciones, funciones lambda. Tipos de datos algebraicos: tipos suma (either, maybe), tipos producto (tuplas, registros), tipos enumerativos, listas y árboles como tipos recursivos. Pattern matching: definición, uso en descomposición de estructuras, ejemplos en lenguajes funcionales. Recursión: recursión estructural sobre listas y árboles, optimización con recursión de cola. Monadas: concepto, leyes de las monadas, ejemplos (Maybe, IO, State), uso para manejar efectos secundarios en lenguajes puros. Implementación práctica: programación funcional en lenguajes como Haskell o Scala, resolución de problemas clásicos (factorial, Fibonacci, quicksort funcional).",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 14,
    name: "Construcción de Interfaces de Usuario",
    info: "Introducción al diseño de interfaces de usuario: conceptos de usabilidad, accesibilidad, experiencia de usuario (UX). Principios de diseño: consistencia, feedback, affordance, modelos mentales del usuario. Prototipado: herramientas (Figma, Adobe XD), creación de wireframes y mockups. Tecnologías frontend: HTML (estructura semántica, formularios), CSS (estilos, flexbox, grid, responsive design), JavaScript (manipulación del DOM, eventos). Frameworks de UI: introducción a React, Vue o Angular, componentes reutilizables, estado y props. Interacción usuario-sistema: manejo de eventos (clics, teclado), validación de formularios, animaciones básicas. Diseño centrado en el usuario: metodologías (entrevistas, pruebas de usabilidad), iteración basada en retroalimentación. Accesibilidad: estándares WAI-ARIA, diseño inclusivo para personas con discapacidades. Integración con backend: consumo de APIs REST, manejo de datos dinámicos.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 15,
    name: "Algoritmos",
    info: "Introducción al diseño y análisis de algoritmos: definición de algoritmo, propiedades (finitud, determinismo, efectividad), ejemplos básicos. Técnicas de diseño: divide y conquista (mergesort, quicksort), programación dinámica (Fibonacci, mochila), algoritmos voraces (Kruskal, Prim). Análisis de complejidad: notación asintótica (Big-O, Omega, Theta), análisis de tiempo y espacio, casos promedio y peor caso. Algoritmos de búsqueda: búsqueda lineal, búsqueda binaria, análisis comparativo. Algoritmos de ordenamiento: burbuja, inserción, selección, mergesort, quicksort, heapsort, estabilidad y rendimiento. Estructuras de datos avanzadas: árboles de búsqueda binaria, heaps, grafos (representación con matrices y listas de adyacencia). Algoritmos sobre grafos: búsqueda en profundidad (DFS), búsqueda en amplitud (BFS), caminos mínimos (Dijkstra). Problemas clásicos: torres de Hanoi, problema del viajante (TSP), ejemplos de implementación.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 16,
    name: "Estrategias de Persistencia",
    info: "Introducción a la persistencia de datos: definición, diferencias entre almacenamiento volátil y persistente, importancia en sistemas de software. Modelos de persistencia: bases de datos relacionales (estructura, normalización), bases NoSQL (clave-valor, documentos, columnas, grafos). Mapeo objeto-relacional (ORM): conceptos de ORM, frameworks (Hibernate, Entity Framework, SQLAlchemy), mapeo de clases a tablas, relaciones (uno a muchos, muchos a muchos). Consultas avanzadas en SQL: joins complejos, subconsultas correlacionadas, índices para optimización, vistas materializadas. Persistencia en bases NoSQL: características (escalabilidad, flexibilidad), ejemplos (MongoDB, Cassandra), diseño de esquemas. Estrategias de acceso a datos: patrones (DAO, Repository), caching (Redis, Memcached), manejo de transacciones distribuidas. Rendimiento y escalabilidad: particionamiento, sharding, replicación, consistencia vs. disponibilidad (teorema CAP). Buenas prácticas: manejo de conexiones, prevención de inyección SQL, auditoría de datos.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 17,
    name: "Laboratorio de Sistemas Operativos y Redes",
    info: "Introducción práctica a sistemas operativos y redes: configuración y administración de sistemas Linux/Windows. Gestión de procesos: uso de comandos (ps, top, taskmgr), creación de scripts para automatización, monitoreo de recursos. Configuración de redes: asignación de direcciones IP estáticas y dinámicas (DHCP), configuración de máscaras de subred, gateways. Protocolos de red: análisis de paquetes con Wireshark, configuración de servicios (DNS, HTTP), uso de herramientas (ping, traceroute, netstat). Seguridad básica: configuración de firewalls (iptables, Windows Firewall), permisos de usuario, cifrado de comunicaciones. Virtualización: introducción a máquinas virtuales (VirtualBox, VMware), creación y gestión de VMs. Prácticas de laboratorio: instalación de SO, configuración de redes locales, resolución de problemas de conectividad, simulación de ataques básicos (escaneo de puertos). Documentación: redacción de informes técnicos sobre configuraciones realizadas.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 18,
    name: "Análisis Matemático",
    info: "Introducción al cálculo diferencial e integral: conceptos de límite, continuidad, propiedades de funciones continuas. Derivadas: definición, reglas de derivación (producto, cociente, cadena), derivadas de funciones trigonométricas, logarítmicas y exponenciales, aplicaciones (máximos, mínimos, puntos de inflexión). Integrales: integral definida e indefinida, teorema fundamental del cálculo, métodos de integración (sustitución, por partes, fracciones parciales). Series numéricas: convergencia y divergencia, criterios (comparación, razón, raíz), series geométricas y armónicas. Funciones de varias variables: derivadas parciales, gradiente, matriz hessiana, optimización con restricciones (multiplicadores de Lagrange). Aplicaciones: cálculo de áreas, volúmenes, longitud de curvas, modelado matemático en problemas físicos e informáticos.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 19,
    name: "Lógica y Programación",
    info: "Fundamentos de lógica formal: lógica proposicional (conectivos, tablas de verdad, formas normales), lógica de primer orden (cuantificadores, predicados, modelos). Técnicas de demostración: deducción natural, demostración por contradicción, demostración directa, ejemplos en matemática e informática. Programación lógica: introducción al paradigma lógico, sintaxis de Prolog (hechos, reglas, consultas), unificación y resolución. Búsqueda en espacios de estados: backtracking, árboles de búsqueda, optimización con poda. Aplicaciones: resolución de problemas lógicos (sudoku, 8 reinas), sistemas expertos básicos, razonamiento automático. Relación con otros paradigmas: comparación con programación funcional e imperativa, ventajas en problemas de inteligencia artificial. Implementación práctica: escritura de programas en Prolog, integración con lenguajes imperativos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 20,
    name: "Elementos de Ingeniería de Software",
    info: "Introducción a la ingeniería de software: definición, objetivos, diferencias con programación ad-hoc. Ciclo de vida del software: modelos clásicos (cascada, espiral), modelos iterativos (prototipado, incremental), metodologías ágiles (Scrum, XP). Requerimientos: elicitación (entrevistas, encuestas), especificación (casos de uso, historias de usuario), validación (revisiones, prototipos). Diseño de software: conceptos de arquitectura, diagramas UML (clases, secuencia, casos de uso), principios de diseño modular (cohesión, acoplamiento). Pruebas de software: tipos (unitarias, integración, sistema), estrategias (caja negra, caja blanca), herramientas de automatización (JUnit, Selenium). Gestión de configuración: control de versiones (Git), integración continua. Documentación: redacción de especificaciones técnicas, manuales de usuario. Ética en ingeniería de software: responsabilidad profesional, calidad del producto.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 21,
    name: "Seguridad de la Información",
    info: "Introducción a la seguridad informática: definición, importancia, diferencia entre seguridad de la información y ciberseguridad. Amenazas y vulnerabilidades: tipos de ataques (malware, phishing, DDoS), análisis de riesgos, evaluación de impacto. Criptografía: fundamentos (cifrado simétrico: AES, DES; cifrado asimétrico: RSA, claves públicas/privadas), funciones hash (MD5, SHA), firmas digitales. Seguridad en redes: protocolos seguros (SSL/TLS, IPsec), configuración de firewalls, detección de intrusos (IDS). Seguridad en sistemas operativos: gestión de permisos, autenticación (contraseñas, multifactor), auditoría de seguridad. Políticas de seguridad: diseño de políticas, cumplimiento normativo (ISO 27001), planes de respuesta a incidentes. Prácticas de laboratorio: cifrado de mensajes, análisis de vulnerabilidades con herramientas (Nmap, Metasploit), configuración de VPNs.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 22,
    name: "Materia UNAHUR I",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 23,
    name: "Inglés II",
    info: "Desarrollo de habilidades avanzadas en lectura y escritura técnica en inglés: comprensión de textos complejos (artículos científicos, white papers, documentación técnica avanzada). Estrategias de lectura: inferencia de significados por contexto, deducción de términos técnicos, análisis crítico de contenido. Vocabulario técnico: términos específicos de informática (networking, algorithms, software engineering), construcción de glosarios. Escritura técnica: redacción de resúmenes, informes técnicos breves, correos profesionales en inglés. Introducción a la escucha: comprensión de charlas técnicas (podcasts, conferencias TED), identificación de ideas principales y detalles. Gramática avanzada: tiempos verbales compuestos (present perfect, past perfect), voz pasiva en descripciones técnicas, oraciones condicionales. Práctica oral: exposición de temas técnicos en inglés, debates sobre tecnología. Uso de herramientas: traducción asistida, diccionarios técnicos online.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 24,
    name: "Matemática III",
    info: "Ecuaciones diferenciales ordinarias: definición, clasificación (lineales, no lineales), métodos de resolución (separación de variables, factores integrantes), aplicaciones en modelado (crecimiento poblacional, circuitos). Transformadas: transformada de Laplace (definición, propiedades, resolución de ecuaciones diferenciales), transformada de Fourier (análisis de señales, aplicaciones en informática). Optimización: funciones de varias variables, gradiente, Hessiano, extremos con restricciones (multiplicadores de Lagrange), aplicaciones en machine learning y algoritmos. Series de potencias: convergencia, radio de convergencia, desarrollo en series de Taylor y Maclaurin. Análisis numérico introductorio: aproximación de soluciones (método de Euler), errores de redondeo y truncamiento.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 25,
    name: "Programación Concurrente",
    info: "Introducción a la programación concurrente: definición, diferencias con programación secuencial, aplicaciones (multitarea, servidores). Modelos de concurrencia: hilos (threads), procesos, actores, memoria compartida vs. paso de mensajes. Gestión de hilos: creación y terminación (Java Threads, POSIX threads), estados de los hilos, prioridades. Sincronización: problemas clásicos (sección crítica, productor-consumidor), mecanismos (locks, semáforos, monitores), condiciones de carrera y su prevención. Deadlocks: definición, condiciones necesarias, detección y resolución (algoritmo del banquero). Herramientas y lenguajes: uso de bibliotecas (Java Concurrency, pthreads), introducción a lenguajes concurrentes (Go, Erlang). Análisis de rendimiento: overhead de concurrencia, escalabilidad, profiling de aplicaciones concurrentes. Prácticas: implementación de problemas concurrentes (buffer circular, lectores-escritores).",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 26,
    name: "Ingeniería de Requerimientos",
    info: "Introducción a la ingeniería de requerimientos: definición, importancia en el desarrollo de software, rol del ingeniero de requerimientos. Elicitación de requerimientos: técnicas (entrevistas, cuestionarios, observación, brainstorming), identificación de stakeholders, análisis de necesidades. Especificación de requerimientos: redacción de documentos (SRS), formatos (historias de usuario, casos de uso), requisitos funcionales y no funcionales (rendimiento, seguridad, usabilidad). Validación de requerimientos: revisiones formales, prototipos, pruebas de aceptación, trazabilidad. Gestión de requerimientos: herramientas (JIRA, Trello), manejo de cambios, priorización (MoSCoW, Kano). Problemas comunes: ambigüedad, incompletitud, conflictos entre stakeholders, técnicas de resolución. Relación con otros procesos: integración con diseño y pruebas. Prácticas: elaboración de un documento de requerimientos para un proyecto pequeño.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 27,
    name: "Desarrollo de Aplicaciones",
    info: "Introducción al desarrollo full-stack: definición, arquitectura cliente-servidor, tecnologías involucradas. Backend: diseño de APIs REST (endpoints, métodos HTTP, códigos de estado), frameworks (Spring, Express.js, Django), autenticación (JWT, OAuth). Frontend: desarrollo de interfaces dinámicas (React, Angular), manejo de estado (Redux, Vuex), integración con APIs. Bases de datos: diseño de esquemas relacionales y NoSQL, consultas avanzadas, optimización. Integración: comunicación frontend-backend, manejo de errores, validación de datos. Despliegue: conceptos de DevOps (CI/CD), uso de contenedores (Docker), alojamiento (AWS, Heroku). Metodologías ágiles: aplicación de Scrum en desarrollo, sprints, retrospectivas. Proyecto práctico: desarrollo de una aplicación completa (ejemplo: sistema de gestión de tareas), desde diseño hasta despliegue.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 28,
    name: "Probabilidad y Estadística",
    info: "Introducción a la teoría de probabilidad: definición, espacio muestral, eventos, axiomas de probabilidad, probabilidad condicional, teorema de Bayes. Variables aleatorias: discretas (binomial, Poisson), continuas (normal, exponencial), funciones de distribución y densidad, valor esperado, varianza. Distribuciones: propiedades, aplicaciones en informática (tiempos de respuesta, fallos de sistemas). Estadística descriptiva: medidas de tendencia central (media, mediana, moda), medidas de dispersión (varianza, desviación estándar), representación gráfica (histogramas, boxplots). Inferencia estadística: estimación puntual e intervalos de confianza, pruebas de hipótesis (t-test, chi-cuadrado), nivel de significancia. Regresión: regresión lineal simple, método de mínimos cuadrados, correlación. Aplicaciones: análisis de datos en software, predicción de rendimiento, evaluación de algoritmos.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 29,
    name: "Gestión de Proyectos de Desarrollo de Software",
    info: "Introducción a la gestión de proyectos: definición, objetivos, ciclo de vida de un proyecto (inicio, planificación, ejecución, monitoreo, cierre). Metodologías: PMBOK (áreas de conocimiento: alcance, tiempo, costo, calidad, riesgos), Scrum (roles, artefactos, eventos), comparación con enfoques tradicionales. Planificación: definición de alcance, estructura de desglose del trabajo (WBS), cronogramas (diagramas de Gantt, PERT), asignación de recursos. Estimación: técnicas (puntos de función, COCOMO, estimación por analogía), manejo de incertidumbre. Gestión de riesgos: identificación, análisis cualitativo y cuantitativo, estrategias de mitigación. Herramientas: software de gestión (MS Project, Jira), control de versiones (Git). Monitoreo y control: métricas (velocidad, burndown), reuniones de seguimiento, ajustes al plan. Cierre: entrega del producto, documentación final, lecciones aprendidas. Prácticas: simulación de un proyecto de software en equipo.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 30,
    name: "Lenguajes Formales y Autómatas",
    info: "Introducción a la teoría de lenguajes formales: definición de lenguaje, alfabeto, cadenas, gramáticas. Autómatas finitos: determinísticos (DFA) y no determinísticos (NFA), equivalencia entre DFA y NFA, conversión, aplicaciones (expresiones regulares). Expresiones regulares: sintaxis, propiedades, conversión a autómatas, uso en búsqueda de patrones. Lenguajes regulares: propiedades de cierre, lema de bombeo para lenguajes regulares. Gramáticas: jerarquía de Chomsky (tipo 0, 1, 2, 3), gramáticas libres de contexto, árboles de derivación. Autómatas de pila: definición, lenguajes aceptados, ejemplos (balanceo de paréntesis). Máquinas de Turing: definición, componentes (cinta, cabezal, estados), variantes (multicinta, no determinística), ejemplos de diseño. Aplicaciones: compiladores, verificación de sistemas, fundamentos de computabilidad.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 31,
    name: "Programación con Objetos III",
    info: "Conceptos avanzados de diseño orientado a objetos: principios SOLID aplicados en profundidad, patrones de diseño estructurales (composite, decorator, facade) y de comportamiento (strategy, command, state). Reflexión: introspección de clases y objetos, uso en frameworks (Java Reflection, Python inspect). Metaprogramación: generación dinámica de código, decoradores, metaclasses. Arquitectura de software orientada a objetos: diseño de sistemas modulares, inyección de dependencias, contenedores IoC (Spring, Guice). Programación reactiva: introducción a flujos reactivos (RxJava, Reactive Streams), manejo de eventos asíncronos. Optimización de código: profiling de aplicaciones OO, detección de cuellos de botella, refactoring avanzado. Prácticas: desarrollo de un sistema complejo (ejemplo: simulador de eventos) usando patrones y herramientas modernas.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 32,
    name: "Materia UNAHUR II",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 33,
    name: "Práctica Profesional Supervisada",
    info: "Introducción a la práctica profesional: objetivos, importancia de la vinculación con el entorno laboral, roles del estudiante y supervisor. Desarrollo de un proyecto real: identificación de un problema en un contexto profesional (empresa, institución, comunidad), análisis de requerimientos, diseño de una solución tecnológica. Metodología de trabajo: aplicación de conocimientos adquiridos (programación, bases de datos, redes), uso de herramientas modernas (Git, Docker, frameworks). Documentación: redacción de un informe técnico detallado (planteo del problema, solución propuesta, implementación, resultados), diagramas y manuales de uso. Presentación: exposición oral del proyecto ante un tribunal, defensa de decisiones técnicas y metodológicas. Evaluación: cumplimiento de objetivos, calidad de la solución, impacto en el entorno. Reflexión: análisis de aprendizajes, desafíos enfrentados, propuestas de mejora.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 34,
    name: "Teoría de la Computación",
    info: "Introducción a la computabilidad: definición, problemas decidibles e indecidibles, máquina de Turing como modelo universal. Modelos de cómputo: autómatas finitos, autómatas de pila, máquinas de Turing (determinísticas, no determinísticas, multicinta), equivalencia entre modelos. Lenguajes y gramáticas: lenguajes regulares, libres de contexto, sensibles al contexto, irrestringidos, lemas de bombeo para cada tipo. Computabilidad: tesis de Church-Turing, problema de la parada (halting problem), reducción y problemas indecidibles. Complejidad computacional: clases P, NP, NP-completo, ejemplos (SAT, TSP), teorema de Cook-Levin. Reducciones: uso de reducciones para probar NP-completitud, ejemplos prácticos. Aplicaciones: fundamentos teóricos de compiladores, verificación formal, límites de la computación.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 35,
    name: "Arquitectura de Software I",
    info: "Introducción a la arquitectura de software: definición, importancia, diferencia con diseño detallado. Estilos arquitectónicos: monolítico, cliente-servidor, en capas, orientado a servicios (SOA), microservicios, ventajas y desventajas de cada uno. Principios de diseño: modularidad (cohesión, acoplamiento), separación de responsabilidades, extensibilidad. Patrones arquitectónicos: MVC, publish-subscribe, event-driven, ejemplos de implementación. Documentación: vistas arquitectónicas (4+1), diagramas UML (despliegue, componentes), descripción de decisiones arquitectónicas. Herramientas: frameworks para microservicios (Spring Boot, Flask), middleware (RabbitMQ, Kafka). Calidad: atributos de calidad (escalabilidad, mantenibilidad, rendimiento), métricas para evaluación. Prácticas: diseño de una arquitectura para un sistema distribuido pequeño (ejemplo: aplicación de mensajería).",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 36,
    name: "Sistemas Distribuidos y Tiempo Real",
    info: "Introducción a los sistemas distribuidos: definición, características (ausencia de reloj global, concurrencia, fallos independientes), aplicaciones (cloud computing, blockchain). Modelos: cliente-servidor, peer-to-peer, arquitecturas basadas en eventos. Comunicación: protocolos (RPC, mensajería), middleware (CORBA, gRPC), serialización (JSON, Protobuf). Sincronización: relojes lógicos (Lamport, vectoriales), algoritmos de exclusión mutua distribuida. Consenso: algoritmos (Paxos, Raft), tolerancia a fallos (replicación, consistencia eventual). Sistemas de tiempo real: definición, tipos (duro, blando), planificación (Rate Monotonic, EDF), ejemplos (sistemas embebidos). Diseño: especificación de requisitos temporales, manejo de latencia, verificación de cumplimiento. Prácticas: implementación de un sistema distribuido simple (ejemplo: chat P2P) y un sistema de tiempo real (controlador básico).",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 37,
    name: "Tesina de Licenciatura",
    info: "Desarrollo de un proyecto integrador o tesis como culminación de la carrera: elección de un tema de investigación o desarrollo tecnológico relevante en informática. Fases del proyecto: definición del problema, revisión bibliográfica, planteo de objetivos, diseño de la solución (metodología, herramientas, tecnologías). Implementación: desarrollo práctico de un prototipo, sistema o análisis teórico, uso de técnicas aprendidas (programación, bases de datos, redes). Documentación: redacción de un trabajo escrito detallado (introducción, marco teórico, metodología, resultados, conclusiones), uso de normas académicas (APA, IEEE). Presentación: defensa oral ante un tribunal, exposición de 20-30 minutos, respuesta a preguntas y críticas. Evaluación: originalidad, profundidad técnica, calidad de la implementación, claridad en la comunicación. Reflexión: análisis del impacto del proyecto, posibles mejoras, aprendizajes adquiridos.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 5,
    hsTotal: 160,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 38,
    name: "Materia Optativa I",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 39,
    name: "Características de Lenguajes de Programación",
    info: "Introducción al estudio de lenguajes de programación: definición, evolución histórica (máquina, ensamblador, alto nivel), clasificación (imperativos, funcionales, lógicos, orientados a objetos). Sintaxis y semántica: gramáticas formales, análisis sintáctico, semántica operacional, denotacional y axiomática. Tipado: sistemas de tipos (estático, dinámico, fuerte, débil), inferencia de tipos, polimorfismo de tipos. Gestión de memoria: asignación estática, dinámica, recolector de basura (mark-and-sweep, referencia counting). Concurrencia: modelos soportados (hilos, actores, CSP), ejemplos en lenguajes (Java, Erlang, Go). Paradigmas específicos: características de lenguajes funcionales (Haskell), lógicos (Prolog), orientados a objetos (Smalltalk). Evaluación de lenguajes: criterios (legibilidad, expresividad, eficiencia), comparación práctica (C vs. Python). Prácticas: análisis de fragmentos de código en distintos lenguajes, implementación de un problema en múltiples paradigmas.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 40,
    name: "Arquitectura de Software II",
    info: "Conceptos avanzados de arquitectura de software: diseño de sistemas a gran escala, arquitecturas cloud-native, serverless computing. Patrones avanzados: CQRS (Command Query Responsibility Segregation), Domain-Driven Design (DDD), event sourcing, ejemplos de implementación. Escalabilidad: estrategias horizontales y verticales, balanceo de carga, sharding, caching distribuido (Redis). Tolerancia a fallos: diseño resiliente, circuit breakers, retry patterns, caos engineering. Monitoreo y observabilidad: métricas (latencia, throughput), logs, trazas distribuidas (Jaeger, Zipkin). Integración: APIs avanzadas (GraphQL, gRPC), sistemas de mensajería (Kafka, RabbitMQ). Calidad: evaluación de trade-offs (rendimiento vs. mantenibilidad), refactoring arquitectónico. Prácticas: diseño e implementación de un sistema escalable (ejemplo: plataforma de streaming), uso de herramientas modernas.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 41,
    name: "Arquitectura de Computadoras",
    info: "Introducción a la arquitectura de computadoras avanzada: evolución de arquitecturas (CISC, RISC), comparación de paradigmas. Componentes de la CPU: pipeline (etapas, riesgos: datos, control, estructurales), predicción de saltos, ejecución fuera de orden. Jerarquía de memoria: caché (niveles, mapeo: directo, asociativo), optimización de acceso (prefetching, locality), memoria virtual avanzada. Paralelismo: arquitecturas multi-core, hyper-threading, GPUs, ejemplos (Intel, ARM). Interconexión: buses (PCIe, USB), redes en chip (NoC). Sistemas embebidos: características, diseño de bajo consumo, ejemplos (Raspberry Pi, Arduino). Herramientas: simulación de arquitecturas (gem5, QEMU), análisis de rendimiento (benchmarks). Prácticas: diseño de un procesador simple en un simulador, optimización de código para caché.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 42,
    name: "Materia Optativa II",
    info: null,
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: true,
  },
  {
    id: 43,
    name: "Parseo y Generación de Código",
    info: "Introducción a los compiladores: estructura (análisis léxico, sintáctico, semántico, optimización, generación de código), ejemplos de compiladores (GCC, LLVM). Análisis léxico: definición de tokens, autómatas finitos, herramientas (Lex, Flex), implementación de un lexer. Análisis sintáctico: gramáticas libres de contexto, parsers top-down (descendente recursivo), bottom-up (LR, LALR), herramientas (Yacc, Bison). Tablas de símbolos: estructura, manejo de ámbitos, resolución de nombres. Análisis semántico: verificación de tipos, chequeo de declaraciones, generación de árboles sintácticos abstractos (AST). Optimización: transformaciones (eliminación de código muerto, inlining), análisis de flujo de datos. Generación de código: traducción a código intermedio (IR como LLVM), generación de código máquina, ejemplos en ensamblador. Prácticas: desarrollo de un compilador simple para un lenguaje minimalista.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 44,
    name: "Ejercicio Profesional",
    info: "Introducción al ejercicio profesional en informática: roles y responsabilidades del profesional, ética en la profesión (códigos de ética ACM, IEEE). Aspectos legales: propiedad intelectual (patentes, derechos de autor), licencias de software (GPL, MIT), protección de datos (GDPR, leyes locales). Contratos: tipos (laborales, consultoría), cláusulas comunes, negociación. Gestión de carrera: habilidades blandas (comunicación, trabajo en equipo), construcción de portafolio, entrevistas técnicas. Problemáticas éticas: privacidad, sesgos en IA, impacto social de la tecnología, casos de estudio (Cambridge Analytica, deepfakes). Prácticas: análisis de casos reales, redacción de contratos simulados, debates sobre ética tecnológica.",
    infoUrl: null,
    area: "APyS",
    hsWeekly: 3,
    hsTotal: 48,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 45,
    name: "Tecnología y Sociedad",
    info: "Introducción a la relación entre tecnología y sociedad: impacto histórico (revolución industrial, era digital), teorías sociológicas (determinismo tecnológico, constructivismo). Tecnología y ética: dilemas (privacidad, automatización, vigilancia), responsabilidad del desarrollador, principios éticos en diseño. Impacto social: brecha digital, inclusión tecnológica, sostenibilidad (residuos electrónicos, consumo energético). Transformación del trabajo: automatización, gig economy, habilidades del futuro. Políticas públicas: regulación de tecnología (IA, datos personales), estándares internacionales. Prospectiva: tendencias emergentes (IoT, biotecnología), análisis de escenarios futuros. Prácticas: investigación de un tema (ejemplo: IA y empleo), presentación de propuestas para mitigar impactos negativos.",
    infoUrl: null,
    area: "APyS",
    hsWeekly: 3,
    hsTotal: 48,
    code: null,
    isPlaceholder: false,
  },

  // Optativas Licenciatura en Informática
  {
    id: 60,
    name: "Bases de Datos II",
    info: `Cuestiones de eficiencia en el acceso a bases de datos: transformación de consultas, hints al motor, trabajo sobre índices. Configuraciones de nivel físico en un motor de base de datos relacional, como tablespaces y replicación. Tipos de datos no-standard en bases de datos, como ser blobs o XML. Implementación física de bases de datos relacionales, en particular: manejo eficiente de archivos, implementación de índices usando árboles B y variantes. Conceptos básicos de Data Mining y Datawarehousing.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 61,
    name: "Fundamentos de Aprendizaje Automático",
    info: `Modelos y métodos computacionales. Clasificación de métodos de aprendizaje. Funciones discriminantes. Aprendizaje Supervisado. Aprendizaje no Supervisado. Modelo probabilístico. Criterios de evaluación de rendimiento. Reducción de dimensión. Análisis de aplicaciones basadas en los métodos estudiados.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 62,
    name: "Introducción a la Bioinformática",
    info: `Conceptos básicos de la genética molecular: leyes de la herencia, genética de poblaciones, genética evolutiva, replicación del ADN, mutación y reparación. Acceso remoto a bancos de datos, bancos genéticos. Análisis de secuencias biológicas, algoritmos asociados. Homologías secuenciales y estructurales.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 63,
    name: "Políticas Públicas en la Sociedad de la Información y la Era Digital",
    info: `Estado y políticas públicas. Cultura abierta, distribuida, libre, producción colaborativa en red. Derechos en la sociedad de la información. Diferentes iniciativas públicas referentes a los estándares abiertos y al software libre. Diversidad e identidades culturales, diversidad lingüística y contenidos locales. Sociedad de la información y el conocimiento. Proyectos de infraestructura y accesibilidad TIC. Acceso y usos: de la red, de los contenidos. Datos abiertos, gobierno electrónico, gobierno abierto, democracia electrónica. Planteo y eventual desarrollo de algún software relacionado con esta temática. Neutralidad en la red.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 64,
    name: "Sistemas de Información Geográfica",
    info: `Introducción a los Sistemas de Información Geográfica (GIS): objetivos, principales tecnologías utilizadas. Posicionamiento: coordenadas, sistemas de referencia, proyecciones, datums, precisión. Modelos de datos: vectorial, raster, interpolación, implementaciones de formatos (SHP, GeoTIFF, KML, otros). Bases de datos espaciales: tipos de datos, consultas, índices. Servidores de Mapas: protocolos, en particular WMS y WFS; tecnologías. Clientes de Mapas: protocolos y tecnologías. Sistemas de Información Geográfica de Escritorio. Implementación de GIS con tecnologías Open Source: servidor de Bases de Datos, servidor de Mapas, clientes Desktop y Web.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 65,
    name: "Introducción al Desarrollo de Videojuegos",
    info: `Panorama de la historia y estado actual de la industria de videojuegos. Diversidad de videojuegos, géneros mejor establecidos. Concepto de game design, relevancia del relato al pensar el concepto de un juego. Aspectos generales en la concepción de videojuegos. Cuestiones de arquitectura de software y hardware pertinentes para el dominio de videojuegos. El proceso de desarrollo de videojuegos, pertinencia de aplicar conceptos ágiles. Características y bondades del modelado de un juego utilizando los conceptos de la programación con objetos: modelado del dominio en función del game design, modelado del comportamiento aprovechando el polimorfismo, modelado del flujo interactivo usando estados. Relevancia del procesamiento de eventos en varios géneros de juegos. Cuestiones ligadas al tratamiento de gráficos: uso de bibliotecas gráficas y buenas prácticas para su integración en una arquitectura de software, sprites, meshes, frustum, cálculo de colisiones.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 66,
    name: "Análisis Estático de Programas y Herramientas Asociadas",
    info: `Análisis de flujo de datos. Análisis intraprocedural. Análisis interprocedural. Análisis de forma. Análisis basado en restricciones. Análisis abstracto 0-CFA y 0-CFA dirigido por sintaxis. Sistemas de tipos y efectos. Análisis de flujo de control. Inferencia de tipos. Efectos. Comportamiento.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 67,
    name: "Semántica de Lenguajes de Programación",
    info: `Definiciones inductivas. Principios de inducción. Semántica operacional y denotacional de lenguajes imperativos. Ordenes parciales completos. Equivalencia. Semántica axiomática de lenguajes imperativos. Aserciones. Corrección. Reglas de Hoare. Conceptos básicos de teoría de dominios. CPOs, productos, espacio de funciones, lifting, sumas. Semántica operacional y denotación de lenguajes funcionales. Estrategias call-by-value, call-by-name, equivalencia.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 68,
    name: "Administración de las Organizaciones",
    info: `Estructura Organizacional - Los Precursores de la Organización Industrial. Los Procesos Corporativos: Decisión, Planeamiento. Control. Funciones de cada área operativa de la Empresa: Comercialización; Económico Financiera; Técnico-Productiva. Compras. Ingeniería Industrial. Investigación y Desarrollo (I+D). Control de Calidad. Higiene y Seguridad Laboral. La Gerencia, Responsabilidad social empresaria. Riesgos Laborales y su prevención. Seguridad en el trabajo. Higiene en el Trabajo. Seguridad Ambiental, Normativa y Legislación. Liderazgo.`,
    infoUrl: null,
    area: "Optativas",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  // Materias UNAHUR
  {
    id: 100,
    name: "Literatura Argentina y Latinoamericana",
    info: "Los usos políticos de la literatura. Las sociedades latinoamericanas, entre la tradición y la modernidad. Localismo y cosmopolitismo. Apropiaciones y modificaciones de estilos tradicionales latinoamericanos y de la cultura universal. La experiencia de la vanguardia en América Latina. Los excluidos y los perseguidos en el siglo XX. Los géneros discursivos y la multiplicidad de emisores. La profesionalización de los escritores y el trabajo con el periodismo. Periodismo y mirada social. Los géneros menores como renovación de la literatura",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 101,
    name: "Historia del Pensamiento Científico y el Desarrollo Tecnológico",
    info: "Ciencia antigua. Introducción a la ciencia antigua. Desarrollo de la matemática y la geometría. Ciencia medieval. Ciencia moderna. El método hipotético deductivo. El método inductivo. El método experimental. Ciencia contemporánea. Ciencia en el siglo XX. Problemas complementarios. Ciencia y ética. Ciencia y religión. Origen del universo: Big Bang. Física nuclear, armas nucleares y guerra fría. Tratado de no proliferación de armas nucleares. Posición argentina y latinoamericana.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 102,
    name: "Ficciones de la patria",
    info: "El nacimiento de la literatura argentina. La independencia y las guerras civiles. Unitarios y federales a través de la literatura. Realis<mo, romanticismo y gótico: el género como elabo-ración de conflictos sociales. La función práctica de la literatura. La gauchesca y los albores del Estado nación. Del Centenario a la “Década Infame”: orden lingüístico y orden social. El problema de la lengua nacional. Campo intelectual y profesionalización del escritor. Las dos tradiciones de la literatura argentina desde la perspectiva del uso del lenguaje. El Estado peronista y la literatura argentina: la circulación de mitos, ficciones y relatos. Los intelectuales ante el peronismo: modos de réplica en la literatura argentina. Los años 70 y el compromiso del escritor. ¿Cómo narrar el horror? La “herencia cultural del Proceso” en el análisis de Fogwill. La poesía argentina de los años 90 ante la debacle de “los grandes relatos”. Cultura joven, consumo y mercado. Neoliberalismo y descomposición social. Objetivismo y habla cotidiana.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 103,
    name: "Innovacion y creatividad",
    info: "Creatividad, e innovación. La innovación y el desarrollo en los campos del conocimiento asociados a las especialidades o de las carreras de la Unahur. El contexto sociocultural de la innovación. ¿Para quiénes innovamos desde la Universidad? Proceso creativo. Diagnóstico de la problemática. Técnicas de generación de ideas. Nociones básicas de neuroeducación para aplicarlas a la generación de ideas-proyecto. Innovación Social Sustentable. Nuevos modelos de liderazgo. Conceptos y desarrollo. Difusión. Formas de organización. Apoyo y financiamiento. Modelos de inversión actuales. Modelos de presupuesto. Financiamiento. Innovación Colaborativa. Organización. Modelo Canvas. Cómo cuento mi proyecto. Cómo muestro mi proyecto.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 104,
    name: "Filosofía. Problemas filosóficos",
    info: "Orígenes de la Filosofía: Grecia. La filosofía entre el arte y la ciencia. La pregunta por el todo. La duda radical. Definiciones críticas de la filosofía. El poder. La multiplicidad de relaciones de poder. El poder y el discurso. La voluntad de poder. Posmodernidad y la sociedad del espectáculo. El fin de los grandes relatos. El cuestionamiento de la idea de progreso y de la teleología de la historia. Posmodernidad y posverdad, sociedad de la comunicación, sociedad de consumo, sociedad del espectáculo. El otro. Existencia precaria y política. La idea de libertad y la ética de la responsabilidad. El debate en torno a los conceptos de tolerancia y hospitalidad. El extranjero.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 105,
    name: "Abordaje de situaciones sociales complejas",
    info: "Paradigma de la complejidad de Edgar Morin y síntesis filosófica de Francisco Leocata. Las redes sociales, el vínculo de la persona con la comunidad y la exclusión. El paradigma de la complejidad. La antropología cristiana. Conceptualización del problema de la droga. Los distintos modelos asistenciales. Los principios de la Doctrina Social de la Iglesia y el Magisterio del Papa Francisco como marco político. Las redes como respuesta a la complejidad.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 106,
    name: "Arte contemporáneo argentino y latinoamericano",
    info: "Los artistas y sus obras más destacadas del siglo XX y XXI en el Arte contemporáneo argentino y latinoamericano. La vanguardia en Latinoamérica, las nuevas técnicas artísticas y los significados del arte. En Argentina siglo XIX: los pintores de la Generación del 80, realismo e historicismo. Siglo XX: La vanguardia como fenómeno social y estético.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 107,
    name: "Arte y tecnología. Escuela de espectadores",
    info: "La mirada del espectador. Exploración de las múltiples conexiones que existen entre la literatura, el cine, el teatro y las artes plásticas y su relación con la tecnología. Artes plásticas. Lengua y literatura. Teatro y representación. Cine y tecnología. Fotografía.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 108,
    name: "Astro: Relación de la Humanidad con el Cosmos",
    info: "Temas y problemas de Astronomía, en una visión general, contextual e histórica. La Astronomía en la Antigüedad. La Esfera Celeste. Elementos de sistemas de coordenadas esféricos. El Tiempo Astronómico. Sistema Solar. Elementos de Astrofísica. Estrellas. Sistemas Estelares. Elementos de Cosmología. Nuevos mundos: Sistemas Extrasolares.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 109,
    name: "Cine documental. Miradas desde el Sur",
    info: "Los profundos cambios a nivel social que se han producido en el mundo contemporáneo y más específicamente en la argentina durante las últimas dos décadas nos dan el marco para poder pensar como el cine documental ha tratado y representado esos acontecimientos. Las vivencias en los cambios individuales y colectivos en perspectiva de derechos humanos, de género, de nuevos hábitos y costumbres en torno al trabajo, la familia, la convivencia entre generaciones las rupturas y los nuevos acuerdos que se producen entre jóvenes y adultos en relación con la forma de entender el mundo contemporáneo. Las implicancias de una posible pedagogía de la mirada partiendo de la necesidad de trabajar los temas complejos que cruzan la vida cotidiana hoy.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 110,
    name: "Ciudadanía activa y compromiso social",
    info: "Las políticas de infancias, el rol del Estado y las nuevas prioridades de agenda en derechos de la niñez y en la reducción de las desigualdades en la Argentina y en el contexto latinoamericano.Las políticas sociales de infancias, la igualdad de oportunidades y de resultados; los paradigmas de políticas de infancia y adolescencia en Argentina y América Latina; la desigualdad y la pobreza en la infancia y adolescencia; la inversión social.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 111,
    name: "Cuando los Pasados No Pasan: lugares de memoria",
    info: "La memoria. La noción de “lugares de memoria”. Genocidios del siglo XX: un acercamiento histórico y conceptual. El terrorismo de Estado en Argentina. Políticas de memoria: derechos humanos ayer y hoy. El memorial de Berlín; la historia de vida de Soghomon Tehlirian; la fecha del 24 de marzo; el pañuelo de las Madres; el Himno Nacional Argentino o el Museo/sitio de memoria ESMA pensados críticamente para conocer el pasado y construir una economía general del pasado en el presente.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 112,
    name: "Ciencias en la cocina",
    info: "Nociones básicas de la química de los alimentos. Calor y temperatura.Entropía y difusión. Física del estado sólido. Reacción de Maillard. Confección de informes delaboratorio",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 113,
    name: "Educación Sexual Integral. Cuando lo esencial es visible a los ojos",
    info: "Introducción a la Educación sexual integral: enfoques y tradiciones de la educación sexual. El paradigma de derechos como marco para las prácticas pedagógicas de ESI: Declaración de los Derechos Humanos y otras leyes que cambiaron paradigmas. La Ley Nacional N°26.150/06. Nueva/os sujetos: niñez y adolescencia; autonomía progresiva; superación del paradigma tutelar. Educación Sexual Integral con perspectiva de género. Géneros y diversidades. El cuerpo como construcción política.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 114,
    name: "Género y sociedad: una nueva mirada para una era más justa",
    info: "El concepto de género: definiciones, argumentos y debates. La lógica binaria en los discursos culturales. Mujeres y trabajo. Relaciones entre identidad, trabajo y género. La categoría de cuidado. El sistema patriarcal. Estructura-individuo. Las relaciones sexuales como relaciones políticas de dominio de los hombres sobre las mujeres. El feminismo de la igualdad y el feminismo de la diferencia. “Lo natural” y “La norma”. Educación desde una perspectiva de género. La escuela y el currículum como espacios de producción de subjetividades. Debates contemporáneos en torno a la pedagogía, los géneros y las sexualidades. Tecnologías corporales, saberes biomédicos y normalización. Aportes de la teoría queer para pensar las diferencias.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 115,
    name: "Introducción a la Imagen. De la imagen fija a la imagen en movimiento",
    info: "Enfoque semiótico y giro pictórico. El problema de la representación. La imagen como signo. La relación entre el significado y el referente. El lenguaje de los nuevos medios. La cultura visual y el estudio de la visualidad. La imagen mediática. La retórica de la imagen. El acto fotográfico. La potencia política de las imágenes. Collage y montaje. El lugar del espectador emancipado. Herramientas del lenguaje visual. Artes y medios visuales y audiovisuales. La estética de lo performativo y la teatralidad.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 116,
    name: "Introducción a la lengua latina",
    info: "Abordaje de la morfosintaxis latina: oraciones originales o adaptadas que empleen un vocabulario específico, reflexión sobre la gramática latina. Notaciones generales e introductorias acerca de los roles asignados en las distintas textualidades de la cultura antigua para la mujer. Abordaje de textos de la oratoria ciceroniana, la poesía lírica de Catulo, Ovidio, Propercio, y la sátira Horaciana y de Juvenal.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 117,
    name: "Introducción al griego antiguo",
    info: "Los temas principales que constituyen el contenido de la asignatura son el estudio de la historia de la lengua griega y su escritura, la morfología nominal y verbal, y la sintaxis.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 118,
    name: "La vida secreta de las rocas",
    info: "Introducción a la geología: origen y evolución del universo, el Sistema Solar y la Tierra. El tiempo geológico. Introducción a la paleontología: evolución e historia de la vida en la Tierra. Registro geológico. Cambio climático. Mineralogía: propiedades de los minerales. Métodos de identificación de minerales. Introducción a la sistemática mineral. El ciclo de las rocas: Procesos endógenos y exógenos. Geología e hidrocarburos: Sistema petrolero convencional y no convencional. Importancia estratégica e implicancias ambientales de las actividades.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 119,
    name: "Literatura y Memoria",
    info: "Literatura y testimonio. El testimonio como resistencia. El testimonio como género literario. Testimonio, verdad y hechos históricos. Los artificios del arte. Jorge Semprún: ¿Cómo contar lo invivible? Memoria testimonial / Memoria ejemplar. Memoria / Historia. Ética y Memoria. Un posible modo de narrar lo invivible: la experiencia de haber muerto. La ficción de la memoria. La novela de ficción y la ciencia ficción como otras posibles respuestas a cómo contar la tragedia social. Los materiales autobiográficos. La verdad como imposible y como motor para escribir en su búsqueda sin cesar. Las ficciones autobiográficas argentinas. Las infancias como insumo de la memoria y la imaginación. La experiencia propia que resuena en la experiencia social.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 120,
    name: "Literatura y Política",
    info: "Relación entre literatura y política. El modo en que grandes acontecimientos del siglo XX impactaron en la literatura de América Latina y, viceversa, el modo en que la literatura latinoamericana impactó sobre su contexto. Poesía política latinoamericana. El retroceso de las utopías y la irrupción de las dictaduras. El neoliberalismo en Argentina. El impacto del peronismo en los intelectuales argentinos. Del antiperonismo a la Revolución Cubana. Alegoría, símbolo y lenguaje cifrado. El cuento como “respuesta” a la coyuntura política. Las letras de rock como literatura. Neoliberalismo, superficialidad y exclusión social en las letras.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 121,
    name: "Mal de tango. La historia argentina a través del tango",
    info: "El nacimiento del tango. Las discontinuidades entre el tango de los comienzos, el tango canción y el tango de vanguardia. La relación entre la historia del tango y la historia de argentina moderna. Eltango canción y los efectos en la ley 1420 de educación. Moral y patriotismo. El período de oro deltango y su relación con el peronismo. Piazzolla y el otro registro del tango.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 122,
    name: "Malvinas: una Causa de nuestra América Latina",
    info: "Los principales argumentos históricos. Descubrimiento, colonización y usurpación. Los argumentos jurídicos: de la usurpación a las Naciones Unidas. Malvinas como causa política de Estado. Integridad territorial y Libre determinación de los pueblos. Otros casos de colonialismo bajo la bandera de la libre determinación. El Atlántico Sur en la geopolítica de América Latina: recursos naturales, depredación y militarización. Soberanía sobre el Atlántico Sur. La Antártida como espacio de disputa.Historia contemporánea de la causa Malvinas: guerra y posguerra. Inglaterra y los problemas de financiamiento de las islas. Intercambios en materia de comunicación, recursos energéticos y educación. El golpe cívico militar de 1976 y el cambio de perspectiva. La decisión de tomar Malvinas y la derrota. Los ochenta y los noventa: la “desmalvinización”. Posneoliberalismo y remalvinización. Malvinas como causa regional. Un nuevo período de desmalvinización.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 123,
    name: "Manipulacion genética en humanos. Historia, mitos y realidades",
    info: "Diversidad y desigualdad. Determinismo biológico en el siglo XIX: frenología, craneometría, antropología criminal, tests de CI. Evolucionismo sociológico y antropológico. Evolucionismos biológicos: teoría darwiniana, embriología, ontogenia y filogenia. El movimiento eugenésico. Tecnologías biomédicas y sociales. El debate ético, político y filosófico en torno a la eugenesia liberal. Tecnología y biopolítica: diversidad y desigualdad. La ética eugenista; Sano/enfermo: medicalización. El diagnóstico preimplantatorio, el CRISPR y otras tecnologías de reproducción humana.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 124,
    name: "Métodos participativos de transformación de conflictos",
    info: "El diálogo colaborativo y la construcción de consensos. Convivencia ambiental. Teoría del Conflicto. Su apreciación y tratamiento como oportunidad de cambio. Comunicación. Conocimientos básicos y aplicación a la vida comunitaria y profesional. Negociación. Técnicas y herramientas. Mediación. Procesos de mediación y su incidencia en la cultura. Facilitación en procesos de abordaje de conflictos intra e inter institucionales. Procesos participativos de prevención temprana y adecuado abordaje de conflictos comunitarios.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 125,
    name: "Modos de ver el Mundo contemporáneo a través del lenguaje audiovisual",
    info: "Los cambios profundos que se han producido en el mundo del trabajo durante los últimos años en las formas de organizar el ciclo laboral y las condiciones laborales como factores de cambios culturales e identitarios. Las vivencias de los cambios individuales y colectivos de los “nuevos” trabajadores que se incorporan hoy en el mercado laboral. Rupturas generacionales que se producen entre jóvenes y adultos en relación con la forma de entender el trabajo. La representación del mundo laboral en el lenguaje audiovisual de las últimas décadas. Forma de influencia de los medios audiovisuales en la percepción del espectador acerca del empleo. Debates sobre las implicancias de una posible pedagogía de la mirada partiendo de la necesidad de trabajar los temas complejos que cruzan la vida cotidiana hoy.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 126,
    name: "No sos vos, es Freud: una introducción al psicoanálisis",
    info: "El surgimiento del psicoanálisis en la historia de occidente y los efectos de su invención en las ciencias del sujeto. El descubrimiento de inconsciente como “saber no sabido” en los actos fallidos y los sueños. La ampliación del concepto de sexualidad, el lugar del amor en el vínculo psicoanalítico y la relación de poder.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 127,
    name: "Nosotrxs y los otrxs. Hacia una práctica profesional inclusiva",
    info: "Los derechos humanos en la historia. Las cuatro generaciones de derechos. Conceptos de igualdad, equidad, discriminación y tolerancia. Racismo y nuevas xenofobias. Poblaciones marginadas,sujetos de derechos. Estrategias de inclusión para la práctica profesional.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 128,
    name: "Pensamiento Ambiental Latinoamericano",
    info: "Introducción al pensamiento ambiental latinoamericano (PAL). La educación y el desarrollo como dos ejes y preocupaciones centrales del PAL. El rol de la educación superior: avances y desafíos. Las concepciones del desarrollo que se disputan al Norte global. La incorporación de la dimensión ambiental en la educación superior. De la EA a la Educación para el Desarrollo Sustentable: un desplazamiento que no sólo es conceptual sino político. El post- desarrollo como alternativa al desarrollo. La ecología política y la propuesta de decolonizar la naturaleza.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 129,
    name: "Pensamiento Nacional",
    info: "Las cosmovisiones en pugna sobre la conquista de América. Una dualidad transhistórica: civilización y barbarie. El concepto de matriz autónoma de pensamiento popular latinoamericano. La conformación del Estado Nacional. Ley 1420. Los gobiernos populares del siglo XX. El carácter fundacional de la Fuerza de Orientación Radical de la Joven Argentina (FORJA). Los imprescindibles: J. J. Hernández Arregui; R. Scalabrini Ortiz. A.Jauretche La cultura popular. E. S. Discépolo. Los medios masivos de comunicación y la construcción de la realidad. La lucha de los postergados: movimientos de mujeres y de poblaciones originarias.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 130,
    name: "Pensar Hurlingham",
    info: "El gobierno local. Los municipios argentinos, una primera aproximación. Nuevas incumbencias, viejas competencias, débiles capacidades estatales. La descentralización y desconcentración municipal. Los servicios públicos municipales. Los servicios urbanos y el hábitat. Región metropolitana y Conurbano bonaerense. La Nueva cuestión social. El Estado de Bienestar. Pobreza y desigualdad. El conurbano. Conceptos fundamentales del desarrollo local. El debate del desarrollo: La matriz moderna del desarrollo. Los pilares políticos y epistemológicos del desarrollo. La visión del desarrollo humano y sustentable. El concepto de territorio local en el desarrollo endógeno. Planificación y ordenamiento territorial. Las políticas públicas locales. Qué son las políticas públicas. La discusión entre políticas públicas universales y focalizadas. La discusión en torno a los derechos y a su ejercicio. El ciclo de las políticas públicas.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 131,
    name: "Repensar la discapacidad: yo estoy al derecho, dado vuelta estás vos",
    info: "Revisión crítica de los modos de entender y abordar la discapacidad a nivel social, las representaciones sociales y los modos de nombrarlas. Historización de los diferentes modos deconceptualización de la discapacidad: modelo de prescindencia y modelo médico-rehabilitador.Discursos y prácticas actuales. Movimientos que dieron lugar al Modelo Social de la discapacidad.Sus postulados principales: la discapacidad como categoría social y política. La construccióndiscursiva de la normalidad: diversidad y alteridad. El concepto de discapacidad como unacategoría de análisis transversal a las disciplinas. La producción colaborativa de accesibilidad.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },

  {
    id: 132,
    name: "Robótica",
    info: "Tecnología y sociedad. Antecedentes históricos y modificaciones para construir autómatas y androides. Definiciones de robótica, mecatrónica y otras asociadas. Disciplinas científicas de esta área de conocimiento. Clasificación de robots en distintas categorías. Partes que componen un dispositivo robótico. Software libre y de código abierto. Tipo de Licencias. La robótica en la actualidad. Aspectos éticos y sociales de la robótica. Introducción a la programación. Interpretación de enunciados y requerimientos. Modelización de forma abstracta de problemas concretos. Pensamiento lógico matemático.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 133,
    name: "Técnicas de investigación en opinión pública",
    info: "Fundamentos de la investigación en Ciencias sociales. Paradigmas: diversidad y coexistencia. El papel de la teoría en el proceso de investigación social. Métodos, objetivos, planteo del problema e hipótesis en la redacción de un proyecto de investigación. Diseño de investigación: conceptos, empiria y decisiones. Tipos de estudios y datos. Herramientas metodológicas y técnicas. Conceptualización y operacionalización. Universo de análisis y muestras. Metodología, métodos y técnicas. Metodología cuantitativa y cualitativa. El trabajo de campo. Investigación social orientada. Alcances y limitaciones del análisis estadístico. Contacto, aceptación de la entrevista y respuesta. Procesamiento. Análisis. Fundamentos del análisis.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 134,
    name: "Una Historia del Rock Nacional",
    info: "Los orígenes del Rock Nacional. Las derivas urbanas como método compositivo. El núcleo fundador. Espacios de sociabilidad. La jerga del rock. Rock y marginalidad. El Cordobazo. La década del 70. Inspiraciones bajo el látigo de la violencia. El apogeo del Rock Nacional. Concepto de “música progresiva”. Folklore y rock. El rock sinfónico. La década del 80. Modernidad o muerte. La guerra de Malvinas como separatoria de aguas. La recuperación democrática. La rebelión punk. De los teatros y estadios al pub y los lugares emblemáticos. El canto popular urbano. La década del 90. La balsa a la deriva. La canción neoliberal. Año 2000 y después. La vuelta de Boedo y Florida: la movida sónica y el rock chabón. Las tribus urbanas. Experimentación y poesía social. Cumbia y protesta social. Últimos años: La producción independiente y las nuevas tecnologías. La muerte del disco.",
    infoUrl: null,
    area: "Otras",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
  },

  // Equivalencias de Licenciatura -> Tecnicatura

  {
    id: 300,
    name: "Matemática para Informática I",
    info: "Lógica proposicional y de primer orden: proposiciones, operaciones lógicas, equivalencias, tablas de verdad, leyes lógicas, simplificaciones. Cuantificadores: universal y existencial, negación, formalización. Razonamiento deductivo: reglas de inferencia, técnicas de prueba. Teoría básica de conjuntos: pertenencia, inclusión, operaciones, propiedades, diagramas de Venn. Aplicaciones en informática: algoritmos y estructuras discretas.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 301,
    name: "Introducción a Lógica y Problemas Computacionales",
    info: "Introducción a la informática: hardware vs. software, historia, futuros (IA, cuántica). Historia del software y lenguajes: paradigmas (imperativo, OO, funcional). Lógica proposicional: conectivos, razonamientos, representación formal. Programas: entornos de desarrollo y ejecución. Programación imperativa: comandos, sensores, estructuras de control, división en subtareas, estructuración.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 302,
    name: "Organización de Computadoras I",
    info: "Historia de la computación. Computadora: modelo Von Neumann. Representación binaria: numéricos (decimal, binario), enteros, racionales, errores. Alfanumérica: ASCII, Unicode. Aritmética binaria: suma, resta, flags. Lógica digital: álgebra de Boole, compuertas, circuitos combinacionales. Unidades: ALU, registros, memoria, E/S, buses. Lenguaje de máquina y ensamblador: instrucciones, ensambladores, compiladores. Microprocesadores y embebidos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 303,
    name: "Programación Estructurada",
    info: "Valores y expresiones: tipos básicos. Estado: variables, ámbito. Terminación y parcialidad. Precondiciones: desarrollo robusto. Programación estructurada: funciones, procedimientos, modularidad. Resolución de problemas: algoritmos básicos. Tipos estructurados: arreglos, registros. Prácticas: implementación en C o Python.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
  },
  {
    id: 304,
    name: "Matemática para Informática II",
    info: "Lógica de primer orden: cuantificadores, predicados. Relaciones binarias: orden, equivalencia, funcionales, propiedades. Diagramas de Hasse. Inducción: demostraciones, aplicaciones. Análisis combinatorio: conteo, permutaciones, combinaciones.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },

  // Tecnicatura en programación

  {
    id: 400,
    name: "Taller de Lenguajes de Marcado y Tecnologías Web",
    info: "Lenguajes de marcado: definición, propósito. Markdown: sintaxis básica. XML y HTML: estructura, etiquetas semánticas HTML5, formularios, multimedia. CSS: selectores, propiedades, diseño responsive. Generación estática: generadores como Jekyll. Generación dinámica: servidores web, conceptos de backend. Prácticas: sitios web con HTML/CSS.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
  },
];
