export const coursesSeed = [
  {
    id: 1,
    name: "Matemática I",
    info: "Elementos de lógica proposicional y de primer orden: Enfoque sintáctico y semántico. Técnicas de prueba. Teoría de la Estructuras Discretas. Definiciones y pruebas estructurales. Estructura de las pruebas formales. Teoría básica de conjuntos. Inducción matemática sobre números naturales. Relaciones binarias: relaciones de orden, relaciones de equivalencia, relaciones funcionales. Elementos básicos de análisis combinatorio.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 2,
    name: "Introducción a la Programación",
    info: "Qué es un programa. Las herramientas del programador: entornos de ejecución y de desarrollo. Paradigmas de Programación: Imperativo, Orientado a Objetos, Funcional, Lógico. Principios de la programación imperativa: acciones y comandos, valores y expresiones, tipos, estado. Terminación y parcialidad. Precondiciones como metodología para desarrollo de software robusto. Principios de la programación estructurada: funciones y procedimientos. Necesidad de darle una estructura a un programa no trivial. Resolución de problemas y algoritmos mediante programas. Estructuras de control. Estructuras de datos básicas: listas y registros.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 3,
    name: "Organización de Computadoras",
    info: "Representación de la información: alfanumérico, numérico, punto fijo y flotante, ASCII. Representación de los datos a nivel máquina. Error. Lenguaje Ensamblador. Sistema de numeración binario. Aritmética de las computadoras: Unidades. Funcionamiento y organización. Arquitectura de Von Neumann. Organización funcional. Unidades funcionales: Unidad Central de Proceso, Unidad de Control, memorias, ciclo de instrucciones, direccionamiento, subsistema de Memoria. Periféricos: conceptos y principio de funcionamiento. Procesadores de Entrada/Salida. Lógica digital: tablas de verdad, equivalencia de fórmulas proposicionales, circuitos combinatorios, circuitos secuenciales. Máquinas algorítmicas. Arquitectura del computador: Componentes de la CPU, memoria principal y secundaria. Subsistema de Entrada/Salida. Lenguaje Máquina. Código fuente y código objeto.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 4,
    name: "Nuevos Entornos y Lenguajes",
    info: "La producción de conocimiento en la cultura digital Web 2.0 - Web 3.0. Lectura y escritura en la nube: hipertextualidad e hipermedialidad. Búsqueda de información: criterios, análisis e interpretación de fuentes de información. Escritura colaborativa. Nuevas formas de producir conocimiento en las redes. Comunidad de práctica. Lenguaje audiovisual: producción e interpretación. Narrativas transmedia: convergencia de formatos. Convergencia tecnológica. Inteligencia colectiva.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 5,
    name: "Estructuras de Datos",
    info: "Recursión sobre listas y árboles. Programas recursivos. Tipos abstractos de datos. Tipos algebraicos: maybe, either, enumerativos, listas, árboles binarios, árboles generales. Estructuras de datos. Estructuras contenedoras: pilas, colas, diccionarios, heaps, árboles balanceados, contenedores basados en representaciones numéricas. Representación de datos en memoria. Nociones de representación e invariante de representación y su utilidad en el diseño e implementación de estructuras de datos. Uso imperativo de estructuras de datos. Iteración en listas y árboles. Modelo de memoria imperativo: stack/heap, alocación de memoria. Punteros. Variables por referencia. Listas encadenadas y sus variantes. Árboles implementados con punteros. Binary heaps implementadas con arrays. Hashing. Análisis de eficiencia e implementación. Algoritmos de recorrido, ordenamiento, búsqueda, ordenamiento y actualización. Clasificación e implementación. Nociones básicas de algoritmos sobre grafos.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 6,
    name: "Programación con Objetos I",
    info: "Conceptos fundantes del paradigma: objeto y mensaje. Concepto de polimorfismo en objetos, comprensión de las ventajas de aprovecharlo. Protocolo/interfaz, concepto de tipo en objetos, comprensión de que un objeto puede asumir distintos tipos. La interfaz como contrato al que se comprometen ciertos objetos, posibilidad de reforzar ese contrato. Estado en el paradigma de objetos: referencias, conocimiento, estado interno. Métodos, clases, herencia, method lookup. Conceptos de responsabilidad y delegación. Colecciones: conceptualización como objetos, caracterización a partir de los conceptos de protocolo y responsabilidad, protocolo, acceso a sus elementos. Testeo automático y repetible. Nociones básicas sobre manejo de errores. Interrupción del flujo de ejecución: modelado mediante estructuras de control, concepto de excepción.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 7,
    name: "Bases de Datos",
    info: "Qué es un modelo de datos, modelos conceptuales, lógicos y físicos. Modelo de entidad-relación: conceptos básicos. Modelo relacional: tabla, atributo, dominio, valor, fila; restricciones de integridad; operaciones que se pueden hacer. SQL: concepto de lenguaje de consulta, sintaxis, concepto de join, agrupamientos, subqueries, joins parciales. Sistemas de Bases de Datos. Diseño y administración de Sistemas de Bases de Datos. Escalabilidad, eficiencia y efectividad. Lenguajes de DBMS. Transacción: concepto, demarcación de transacciones.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 8,
    name: "Inglés I",
    info: "Introducción a la lectura de textos auténticos de géneros específicos de las distintas disciplinas. Estrategias de lectura para la comprensión global de textos escritos en inglés: palabras clave, transparentes, repetidas e índices tipográficos. Palabras conceptuales y estructurales. Organización textual, tema y despliegue temático. Anticipación y predicción. Elaboración del tópico del texto. Técnicas de lectura veloz: skimming y scanning. Cohesión y coherencia. Referentes contextuales: anafóricos y catafóricos; elipsis. Morfología: sufijos y prefijos. Categoría de palabras. Estructura de la información en la definición. Definición de objetos y procesos. Definiciones expandidas. El sintagma nominal. Usos del gerundio (-ing) y del participio pasado (-ed). Instrucciones. Relaciones lógicas entre proposiciones: adición, contraste, causa y efecto, enumeración. Tiempos verbales simples.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },

  // 2do Año
  {
    id: 9,
    name: "Matemática II",
    info: "Espacios vectoriales: definición, propiedades, base y dimensión. Transformaciones lineales: definición, núcleo e imagen, matriz asociada. Sistemas de ecuaciones lineales: definición, resolución. Determinantes: definición y propiedades, regla de Cramer, eliminación gaussiana. Valores y vectores propios: definición, cálculo, diagonalización. Espacios con producto interior: definición, ortogonalidad, proyecciones, método de cuadrados mínimos.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 10,
    name: "Programación con Objetos II",
    info: "Conceptos avanzados del paradigma de objetos: herencia múltiple, mixins, traits, interfaces múltiples. Diseño orientado a objetos: principios SOLID, patrones de diseño básicos (factory, singleton, observer). Polimorfismo avanzado y reflexión. Manejo avanzado de excepciones. Programación genérica: tipos parametrizados, restricciones de tipo. Colecciones avanzadas y su implementación.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 11,
    name: "Sistemas Operativos",
    info: "Conceptos básicos de sistemas operativos. Estructura y organización. Gestión de procesos: estados, planificación, concurrencia, sincronización. Gestión de memoria: segmentación, paginación, memoria virtual. Sistemas de archivos: estructura, implementación, recuperación. Entrada/Salida: principios, controladores, interrupciones. Seguridad y protección en sistemas operativos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 12,
    name: "Inglés II",
    info: "Lectura y comprensión de textos técnicos en inglés. Estrategias avanzadas de lectura: inferencia, deducción de significados por contexto. Vocabulario técnico en informática. Escritura técnica: resúmenes, informes breves. Introducción a la escucha de material técnico en inglés.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 2,
    hsTotal: 32,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 13,
    name: "Probabilidad y Estadística",
    info: "Conceptos básicos de probabilidad: espacio muestral, eventos, reglas de probabilidad. Variables aleatorias: discretas y continuas, distribuciones (binomial, Poisson, normal). Teorema de Bayes. Estadística descriptiva: medidas de tendencia central, dispersión. Inferencia estadística: estimación, pruebas de hipótesis. Regresión lineal simple.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 14,
    name: "Redes de Computadoras I",
    info: "Conceptos básicos de redes. Modelos OSI y TCP/IP. Capa física: medios de transmisión, codificación. Capa de enlace: protocolos, control de acceso al medio, Ethernet. Capa de red: direccionamiento IP, enrutamiento básico. Protocolos de transporte: TCP y UDP. Herramientas de diagnóstico de redes.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },

  // 3er Año
  {
    id: 15,
    name: "Matemática III",
    info: "Cálculo diferencial e integral en una variable: límites, derivadas, integrales definidas e indefinidas, teorema fundamental del cálculo. Series numéricas y de potencias. Funciones de varias variables: derivadas parciales, gradientes, optimización.",
    infoUrl: null,
    area: "CB",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 16,
    name: "Programación Funcional",
    info: "Principios del paradigma funcional: funciones puras, inmutabilidad, recursión. Evaluación perezosa vs. estricta. Tipos de datos algebraicos. Pattern matching. Funciones de orden superior. Monadas y su uso en programación funcional. Implementación en lenguajes funcionales.",
    infoUrl: null,
    area: "AyL",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 17,
    name: "Redes de Computadoras II",
    info: "Protocolos de enrutamiento avanzados. Capa de aplicación: DNS, HTTP, SMTP. Seguridad en redes: cifrado, autenticación, firewalls. Redes inalámbricas y móviles. Diseño de redes locales y de área amplia.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 18,
    name: "Ingeniería de Software I",
    info: "Ciclo de vida del software. Metodologías de desarrollo: cascada, iterativas, ágiles. Requerimientos: elicitación, especificación, validación. Diseño de software: diagramas UML, patrones de diseño. Pruebas de software: unitarias, de integración.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 19,
    name: "Autómatas y Lenguajes Formales",
    info: "Conceptos básicos de teoría de autómatas. Autómatas finitos: determinísticos y no determinísticos. Expresiones regulares. Lenguajes regulares. Gramáticas: jerarquía de Chomsky. Máquinas de Turing: definición, propiedades, aplicaciones.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },

  // 4to Año
  {
    id: 20,
    name: "Ingeniería de Software II",
    info: "Gestión de proyectos de software: planificación, estimación, riesgos. Arquitectura de software: estilos arquitectónicos, microservicios. Calidad de software: métricas, estándares. Mantenimiento y evolución del software. Herramientas CASE.",
    infoUrl: null,
    area: "ISBDySI",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 21,
    name: "Computación Paralela y Distribuida",
    info: "Conceptos de computación paralela: modelos, arquitecturas. Programación paralela: hilos, MPI, OpenMP. Computación distribuida: sistemas cliente-servidor, P2P. Algoritmos distribuidos: sincronización, consenso. Tolerancia a fallos.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 22,
    name: "Inteligencia Artificial",
    info: "Introducción a la IA. Búsqueda: algoritmos informados y no informados. Representación del conocimiento: lógica, redes semánticas. Aprendizaje automático: supervisado, no supervisado, redes neuronales básicas. Procesamiento de lenguaje natural y visión por computadora.",
    infoUrl: null,
    area: "TC",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 23,
    name: "Seguridad Informática",
    info: "Conceptos básicos de seguridad. Criptografía: simétrica, asimétrica, hash. Amenazas y vulnerabilidades. Seguridad en redes y sistemas operativos. Políticas de seguridad y auditoría.",
    infoUrl: null,
    area: "ASOyR",
    hsWeekly: 6,
    hsTotal: 96,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },

  // 5to Año
  {
    id: 24,
    name: "Seminario de Actualización",
    info: "Temas emergentes en informática: tendencias tecnológicas, nuevos paradigmas, casos de estudio. Análisis crítico de artículos científicos y técnicos. Presentación de proyectos o investigaciones.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 4,
    hsTotal: 64,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 25,
    name: "Práctica Profesional Supervisada",
    info: "Desarrollo de un proyecto real supervisado. Aplicación de conocimientos adquiridos en un entorno profesional. Documentación y presentación de resultados. Evaluación de impacto y viabilidad.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 8,
    hsTotal: 128,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
  {
    id: 26,
    name: "Trabajo Final de Licenciatura",
    info: "Elaboración de un proyecto integrador o tesis. Investigación, desarrollo e implementación. Presentación y defensa ante un tribunal.",
    infoUrl: null,
    area: "Otros",
    hsWeekly: 10,
    hsTotal: 160,
    code: null,
    isPlaceholder: false,
    parentOptionId: null,
  },
];
